
var init = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

function g(){p.buffer!=aa.buffer&&ba();return aa}function q(){p.buffer!=aa.buffer&&ba();return ca}function t(){p.buffer!=aa.buffer&&ba();return da}function ea(){p.buffer!=aa.buffer&&ba();return fa}function u(){p.buffer!=aa.buffer&&ba();return ha}function w(){p.buffer!=aa.buffer&&ba();return ia}function ja(){p.buffer!=aa.buffer&&ba();return ka}var z=moduleArg,la,na,oa=new Promise((a,b)=>{la=a;na=b}),A=self.name?.startsWith("em-pthread");z.noInitialRun=!0;z.locateFile&&(_scriptName=z.locateFile("magick.js"));
var pa=Object.assign({},z),qa=[],ra="",sa,ta;ra=self.location.href;_scriptName&&(ra=_scriptName);ra.startsWith("blob:")?ra="":ra=ra.substr(0,ra.replace(/[?#].*/,"").lastIndexOf("/")+1);ta=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};sa=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var ua=console.log.bind(console),B=console.error.bind(console);
Object.assign(z,pa);pa=null;var p,va,wa=!1,xa,aa,ca,da,fa,ha,ia,ya,ka;function ba(){var a=p.buffer;z.HEAP8=aa=new Int8Array(a);z.HEAP16=da=new Int16Array(a);z.HEAPU8=ca=new Uint8Array(a);z.HEAPU16=fa=new Uint16Array(a);z.HEAP32=ha=new Int32Array(a);z.HEAPU32=ia=new Uint32Array(a);z.HEAPF32=ya=new Float32Array(a);z.HEAPF64=ka=new Float64Array(a)}
if(A){var za,Aa=!1;B=function(...b){console.error(b.join(" "))};self.alert=function(...b){postMessage({jd:"alert",text:b.join(" "),Xf:Ba()})};self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.jd;if("load"===d){let e=[];self.onmessage=f=>e.push(f);self.startWorker=()=>{postMessage({jd:"loaded"});for(let f of e)a(f);self.onmessage=a};for(const f of c.Gf)if(!z[f]||z[f].proxy)z[f]=(...h)=>{postMessage({jd:"callHandler",Ff:f,mf:h})},"print"==f&&(ua=z[f]),"printErr"==
f&&(B=z[f]);p=c.$f;ba();za(c.ag)}else if("run"===d){Ca(c.nd);Da(c.nd,0,0,1,0,0);Ea();Fa(c.nd);Aa||(Ga(),Aa=!0);try{Ha(c.Vf,c.te)}catch(e){if("unwind"!=e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?Aa&&Ia():d&&(B(`worker: received unknown command ${d}`),B(c)))}catch(e){throw Ja(),e;}}self.onmessage=a}A||(p=new WebAssembly.Memory({initial:1024,maximum:32768,shared:!0}),ba());var Ka=[],La=[],Ma=[],Na=[];
function Oa(){A||(Pa.root=C.Nc(Pa,{},null),z.noFSInit||C.we||C.Vd(),C.ve=!1,Qa(La))}var Ra=0,Sa=null,Ta=null;function Ua(){Ra--;if(0==Ra&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta)){var a=Ta;Ta=null;a()}}function Va(a){a="Aborted("+a+")";B(a);wa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");na(a);throw a;}var Wa=a=>a.startsWith("data:application/octet-stream;base64,"),Xa;
function Ya(a){return sa(a).then(b=>new Uint8Array(b),()=>{if(ta)var b=ta(a);else throw"both async and sync fetching of the wasm failed";return b})}function Za(a,b,c){return Ya(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{B(`failed to asynchronously prepare wasm: ${d}`);Va(d)})}
function $a(a,b){var c=Xa;return"function"!=typeof WebAssembly.instantiateStreaming||Wa(c)||"function"!=typeof fetch?Za(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){B(`wasm streaming compile failed: ${e}`);B("falling back to ArrayBuffer instantiation");return Za(c,a,b)}))}
function ab(){bb={b:cb,Da:db,x:eb,A:fb,g:gb,p:hb,U:ib,Ba:jb,B:kb,Ka:lb,Fa:mb,k:nb,pa:ob,oa:pb,Ua:qb,na:rb,Xa:sb,Ya:tb,vb:ub,Va:vb,J:wb,Ra:xb,Ma:yb,Ca:zb,$a:Ab,ma:Bb,Pa:Cb,Oa:Db,Y:Eb,Aa:Fb,la:Gb,ya:Hb,za:Ib,ka:Jb,T:Kb,Qa:Lb,xa:Mb,V:Nb,sa:Ob,Za:Pb,fb:Qb,Bb:Rb,db:Sb,Q:Tb,cb:Ub,F:Vb,j:Wb,$:Xb,u:Yb,E:Zb,s:$b,aa:ac,O:bc,gb:cc,P:dc,eb:ec,Wa:fc,Ja:gc,ta:hc,Ga:ic,Ea:jc,ua:kc,W:lc,Ia:Fa,Ta:mc,ia:nc,jb:oc,q:pc,ib:qc,kb:rc,ga:sc,z:tc,M:uc,hb:vc,y:wc,t:xc,yb:yc,zb:zc,wb:Ac,xb:Bc,ja:Cc,Ha:Dc,X:Ec,I:Fc,Sa:Gc,va:Hc,
D:Ic,wa:Jc,qa:Kc,ab:Lc,bb:Mc,v:Nc,L:Oc,ra:Pc,ub:Qc,tb:Rc,_:Sc,Ab:Tc,Na:Uc,Z:Vc,ba:Wc,Gb:Xc,R:Yc,c:Zc,Fb:$c,e:ad,m:bd,o:cd,Db:dd,S:ed,d:fd,ea:gd,ca:hd,K:jd,lb:kd,sb:ld,rb:md,nb:nd,pb:od,ob:pd,l:qd,h:rd,f:sd,ha:td,fa:ud,n:vd,i:wd,w:xd,G:yd,C:zd,r:Ad,Eb:Bd,H:Cd,Cb:Dd,da:Ed,N:Fd,mb:Gd,qb:Hd,a:p,_a:Id,La:Jd};return{a:bb}}var E,F;class Kd{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ld=a=>{a.terminate();a.onmessage=()=>{}},Rd=a=>{0==Md.length&&(Nd(),Od(Md[0]));var b=Md.pop();if(!b)return 6;Pd.push(b);Qd[a.nd]=b;b.nd=a.nd;b.postMessage({jd:"run",Vf:a.Uf,te:a.te,nd:a.nd},a.gf);return 0},Sd=0,Td=(a,b)=>b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN,I=(a,b,...c)=>{for(var d=c.length,e=G(),f=Ud(8*d),h=f>>3,k=0;k<c.length;k++){var l=c[k];ja()[h+k]=l}a=Vd(a,0,d,f,b);H(e);return a};
function Id(a){if(A)return I(0,1,a);xa=a;if(!(Wd||0<Sd)){for(var b of Pd)Ld(b);for(b of Md)Ld(b);Md=[];Pd=[];Qd={};z.onExit?.(a);wa=!0}throw new Kd(a);}var Xd=a=>{if(a instanceof Kd||"unwind"==a)return xa;throw a;};function Yd(a){if(A)return I(1,0,a);Nc(a)}var Nc=a=>{xa=a;if(A)throw Yd(a),"unwind";Id(a)},Md=[],Pd=[],Zd=[],Qd={};function $d(){for(var a=navigator.hardwareConcurrency;a--;)Nd();Ka.unshift(()=>{Ra++;ae(()=>Ua())})}
var ce=a=>{var b=a.nd;delete Qd[b];Md.push(a);Pd.splice(Pd.indexOf(a),1);a.nd=0;be(b)};function Ea(){Zd.forEach(a=>a())}
var Od=a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var h=f.jd;if(f.pe&&f.pe!=Ba()){var k=Qd[f.pe];k?k.postMessage(f,f.gf):B(`Internal error! Worker sent a message "${h}" to target pthread ${f.pe}, but that thread no longer exists!`)}else if("checkMailbox"===h)Ia();else if("spawnThread"===h)Rd(f);else if("cleanupThread"===h)ce(Qd[f.Wf]);else if("loaded"===h)a.loaded=!0,b(a);else if("alert"===h)alert(`Thread ${f.Xf}: ${f.text}`);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===
h)z[f.Ff](...f.mf);else h&&B(`worker sent an unknown command ${h}`)};a.onerror=f=>{B(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit"],e;for(e of d)z.propertyIsEnumerable(e)&&c.push(e);a.postMessage({jd:"load",Gf:c,$f:p,ag:va})});function ae(a){A?a():Promise.all(Md.map(Od)).then(a)}function Nd(){var a=new Worker(_scriptName,{type:"module",name:"em-pthread"});Md.push(a)}
var Qa=a=>{for(;0<a.length;)a.shift()(z)},Ca=a=>{ba();var b=w()[a+52>>2];a=w()[a+56>>2];de(b,b-a);H(b)},M,Ha=(a,b)=>{Wd=Sd=0;a=M.get(a)(b);Wd||0<Sd?xa=a:ee(a)},Wd=z.noExitRuntime||!0,fe="undefined"!=typeof TextDecoder?new TextDecoder:void 0,ge=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&fe)return fe.decode(a.slice(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<
12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},N=(a,b)=>a?ge(q(),a,b):"",cb=(a,b,c,d)=>Va(`Assertion failed: ${N(a)}, at: `+[b?N(b):"unknown filename",c,d?N(d):"unknown function"]),db=(a,b)=>M.get(a)(b),he=[],ie=0,eb=a=>{var b=new je(a);if(0==g()[b.Lc+12]){var c=1;g()[b.Lc+12]=c;ie--}ke(b,!1);he.push(b);le(a);return me(a)},ne=0,fb=()=>{O(0,0);var a=he.pop();oe(a.Te);ne=
0};function ke(a,b){b=b?1:0;g()[a.Lc+13]=b}class je{constructor(a){this.Te=a;this.Lc=a-24}Vd(a,b){w()[this.Lc+16>>2]=0;w()[this.Lc+4>>2]=a;w()[this.Lc+8>>2]=b}}
var nb=a=>{ne||=a;throw ne;},re=a=>{var b=ne;if(!b)return pe(0),0;var c=new je(b);w()[c.Lc+16>>2]=b;var d=w()[c.Lc+4>>2];if(!d)return pe(0),b;for(var e of a){if(0===e||e===d)break;if(qe(e,d,c.Lc+16))return pe(e),b}pe(d);return b},gb=()=>re([]),hb=a=>re([a]),ib=()=>{var a=he.pop();a||Va("no exception to throw");var b=a.Te;if(0==g()[a.Lc+13]){he.push(a);ke(a,!0);var c=0;g()[a.Lc+12]=c;ie++}ne=b;throw ne;},jb=a=>{a&&(a=new je(a),he.push(a),ke(a,!0),ib())},kb=(a,b,c)=>{(new je(a)).Vd(b,c);ne=a;ie++;throw ne;
},lb=()=>ie;function te(a,b,c,d){return A?I(2,1,a,b,c,d):mb(a,b,c,d)}
var mb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(A&&0===e.length)return te(a,b,c,d);a={Uf:c,nd:a,te:d,gf:e};return A?(a.jd="spawnThread",postMessage(a,e),0):Rd(a)},ue=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),a);Va("initRandomDevice")},ve=a=>(ve=ue())(a),we=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&
(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},xe=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=we(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ye=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},ze=a=>{if("/"===a)return"/";a=xe(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ae=(...a)=>
xe(a.join("/")),Be=(a,b)=>xe(a+"/"+b),Ce=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:C.ee();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=we(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},De=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var l=h.length-1;0<=l&&""===h[l];l--);return k>l?[]:h.slice(k,l-k+1)}a=Ce(a).substr(1);b=Ce(b).substr(1);a=c(a.split("/"));
b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Ee=[],Fe=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ge=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var k=a.charCodeAt(++f);h=65536+((h&1023)<<10)|k&1023}if(127>=
h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e},He=[];function Ie(a,b){He[a]={input:[],Xc:[],td:b};Je(a,Ke)}
var Ke={open(a){var b=He[a.node.yd];if(!b)throw new C.Fc(43);a.Oc=b;a.seekable=!1},close(a){a.Oc.td.Ld(a.Oc)},Ld(a){a.Oc.td.Ld(a.Oc)},read(a,b,c,d){if(!a.Oc||!a.Oc.td.Xe)throw new C.Fc(60);for(var e=0,f=0;f<d;f++){try{var h=a.Oc.td.Xe(a.Oc)}catch(k){throw new C.Fc(29);}if(void 0===h&&0===e)throw new C.Fc(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.Oc||!a.Oc.td.Be)throw new C.Fc(60);try{for(var e=0;e<d;e++)a.Oc.td.Be(a.Oc,b[c+e])}catch(f){throw new C.Fc(29);
}d&&(a.node.timestamp=Date.now());return e}},Le={Xe(){return Ee.length?Ee.shift():null},Be(a,b){null===b||10===b?(ua(ge(a.Xc)),a.Xc=[]):0!=b&&a.Xc.push(b)},Ld(a){a.Xc&&0<a.Xc.length&&(ua(ge(a.Xc)),a.Xc=[])},If(){return{ig:25856,kg:5,hg:191,jg:35387,gg:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Jf(){return 0},Kf(){return[24,80]}},Me={Be(a,b){null===b||10===b?(B(ge(a.Xc)),a.Xc=[]):0!=b&&a.Xc.push(b)},Ld(a){a.Xc&&0<a.Xc.length&&(B(ge(a.Xc)),a.Xc=[])}},Oe=a=>{a=65536*
Math.ceil(a/65536);var b=Ne(65536,a);b&&q().fill(0,b,b+a);return b};function Pe(a,b){var c=a.Jc?a.Jc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Jc,a.Jc=new Uint8Array(b),0<a.Pc&&a.Jc.set(c.subarray(0,a.Pc),0))}
var P={ld:null,Nc(){return P.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=24576===(c&61440))||(e=4096===(c&61440));if(e)throw new C.Fc(63);P.ld||(P.ld={dir:{node:{$c:P.Hc.$c,Tc:P.Hc.Tc,sd:P.Hc.sd,ed:P.Hc.ed,Ad:P.Hc.Ad,Bd:P.Hc.Bd,vd:P.Hc.vd,zd:P.Hc.zd,hd:P.Hc.hd},stream:{Vc:P.Ic.Vc}},file:{node:{$c:P.Hc.$c,Tc:P.Hc.Tc},stream:{Vc:P.Ic.Vc,read:P.Ic.read,write:P.Ic.write,Kd:P.Ic.Kd,xd:P.Ic.xd,Hd:P.Ic.Hd}},link:{node:{$c:P.Hc.$c,Tc:P.Hc.Tc,ud:P.Hc.ud},stream:{}},Ne:{node:{$c:P.Hc.$c,Tc:P.Hc.Tc},
stream:C.rf}});c=C.createNode(a,b,c,d);Q(c.mode)?(c.Hc=P.ld.dir.node,c.Ic=P.ld.dir.stream,c.Jc={}):C.isFile(c.mode)?(c.Hc=P.ld.file.node,c.Ic=P.ld.file.stream,c.Pc=0,c.Jc=null):40960===(c.mode&61440)?(c.Hc=P.ld.link.node,c.Ic=P.ld.link.stream):8192===(c.mode&61440)&&(c.Hc=P.ld.Ne.node,c.Ic=P.ld.Ne.stream);c.timestamp=Date.now();a&&(a.Jc[b]=c,a.timestamp=c.timestamp);return c},vg(a){return a.Jc?a.Jc.subarray?a.Jc.subarray(0,a.Pc):new Uint8Array(a.Jc):new Uint8Array(0)},Hc:{$c(a){var b={};b.fe=8192===
(a.mode&61440)?a.id:1;b.Wd=a.id;b.mode=a.mode;b.ne=1;b.uid=0;b.ge=0;b.yd=a.yd;Q(a.mode)?b.size=4096:C.isFile(a.mode)?b.size=a.Pc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.ce=new Date(a.timestamp);b.le=new Date(a.timestamp);b.de=new Date(a.timestamp);b.wd=4096;b.Dd=Math.ceil(b.size/b.wd);return b},Tc(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Pc!=b))if(0==b)a.Jc=null,a.Pc=0;else{var c=a.Jc;a.Jc=new Uint8Array(b);
c&&a.Jc.set(c.subarray(0,Math.min(b,a.Pc)));a.Pc=b}},sd(){throw P.Se;},ed(a,b,c,d){return P.createNode(a,b,c,d)},Ad(a,b,c){if(Q(a.mode)){try{var d=Qe(b,c)}catch(f){}if(d)for(var e in d.Jc)throw new C.Fc(55);}delete a.parent.Jc[a.name];a.parent.timestamp=Date.now();a.name=c;b.Jc[c]=a;b.timestamp=a.parent.timestamp},Bd(a,b){delete a.Jc[b];a.timestamp=Date.now()},vd(a,b){var c=Qe(a,b),d;for(d in c.Jc)throw new C.Fc(55);delete a.Jc[b];a.timestamp=Date.now()},zd(a){var b=[".",".."],c;for(c of Object.keys(a.Jc))b.push(c);
return b},hd(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},ud(a){if(40960!==(a.mode&61440))throw new C.Fc(28);return a.link}},Ic:{read(a,b,c,d,e){var f=a.node.Jc;if(e>=a.node.Pc)return 0;a=Math.min(a.node.Pc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===g().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Jc||a.Jc.subarray)){if(f)return a.Jc=b.subarray(c,c+d),a.Pc=d;if(0===a.Pc&&
0===e)return a.Jc=b.slice(c,c+d),a.Pc=d;if(e+d<=a.Pc)return a.Jc.set(b.subarray(c,c+d),e),d}Pe(a,e+d);if(a.Jc.subarray&&b.subarray)a.Jc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Jc[e+f]=b[c+f];a.Pc=Math.max(a.Pc,e+d);return d},Vc(a,b,c){1===c?b+=a.position:2===c&&C.isFile(a.node.mode)&&(b+=a.node.Pc);if(0>b)throw new C.Fc(28);return b},Kd(a,b,c){Pe(a.node,b+c);a.node.Pc=Math.max(a.node.Pc,b+c)},xd(a,b,c,d,e){if(!C.isFile(a.node.mode))throw new C.Fc(43);a=a.node.Jc;if(e&2||!a||a.buffer!==g().buffer){d=
!0;e=Oe(b);if(!e)throw new C.Fc(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);g().set(a,e)}}else d=!1,e=a.byteOffset;return{Lc:e,se:d}},Hd(a,b,c,d){P.Ic.write(a,b,0,d,c,!1);return 0}}},Re=(a,b,c)=>{var d=`al ${a}`;sa(a).then(e=>{b(new Uint8Array(e));d&&Ua()},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ra++},Se=[],Te=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.Vd();var e=!1;Se.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,
b,c,d),e=!0)});return e},Ue=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ve={EPERM:63,ENOENT:44,ESRCH:71,EINTR:27,EIO:29,ENXIO:60,E2BIG:1,ENOEXEC:45,EBADF:8,ECHILD:12,EAGAIN:6,EWOULDBLOCK:6,ENOMEM:48,EACCES:2,EFAULT:21,ENOTBLK:105,EBUSY:10,EEXIST:20,EXDEV:75,ENODEV:43,ENOTDIR:54,EISDIR:31,EINVAL:28,ENFILE:41,EMFILE:33,ENOTTY:59,ETXTBSY:74,EFBIG:22,ENOSPC:51,ESPIPE:70,EROFS:69,EMLINK:34,EPIPE:64,EDOM:18,ERANGE:68,ENOMSG:49,EIDRM:24,ECHRNG:106,EL2NSYNC:156,EL3HLT:107,EL3RST:108,ELNRNG:109,EUNATCH:110,
ENOCSI:111,EL2HLT:112,EDEADLK:16,ENOLCK:46,EBADE:113,EBADR:114,EXFULL:115,ENOANO:104,EBADRQC:103,EBADSLT:102,EDEADLOCK:16,EBFONT:101,ENOSTR:100,ENODATA:116,ETIME:117,ENOSR:118,ENONET:119,ENOPKG:120,EREMOTE:121,ENOLINK:47,EADV:122,ESRMNT:123,ECOMM:124,EPROTO:65,EMULTIHOP:36,EDOTDOT:125,EBADMSG:9,ENOTUNIQ:126,EBADFD:127,EREMCHG:128,ELIBACC:129,ELIBBAD:130,ELIBSCN:131,ELIBMAX:132,ELIBEXEC:133,ENOSYS:52,ENOTEMPTY:55,ENAMETOOLONG:37,ELOOP:32,EOPNOTSUPP:138,EPFNOSUPPORT:139,ECONNRESET:15,ENOBUFS:42,EAFNOSUPPORT:5,
EPROTOTYPE:67,ENOTSOCK:57,ENOPROTOOPT:50,ESHUTDOWN:140,ECONNREFUSED:14,EADDRINUSE:3,ECONNABORTED:13,ENETUNREACH:40,ENETDOWN:38,ETIMEDOUT:73,EHOSTDOWN:142,EHOSTUNREACH:23,EINPROGRESS:26,EALREADY:7,EDESTADDRREQ:17,EMSGSIZE:35,EPROTONOSUPPORT:66,ESOCKTNOSUPPORT:137,EADDRNOTAVAIL:4,ENETRESET:39,EISCONN:30,ENOTCONN:53,ETOOMANYREFS:141,EUSERS:136,EDQUOT:19,ESTALE:72,ENOTSUP:138,ENOMEDIUM:148,EILSEQ:25,EOVERFLOW:61,ECANCELED:11,ENOTRECOVERABLE:56,EOWNERDEAD:62,ESTRPIPE:135};
function R(a){try{return a()}catch(b){if(!b.code)throw b;if("UNKNOWN"===b.code)throw new C.Fc(28);throw new C.Fc(Ve[b.code]);}}function We(a){return R(()=>{var b=(void 0).Mf(a).mode;S.je&&(b|=(b&292)>>2);return b})}function Xe(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.Nc.Nd.root);b.reverse();return Ae(...b)}
var S={je:!1,ef(){S.je=!!(void 0).platform.match(/^win/);var a=(void 0).fg("constants");a.fs&&(a=a.fs);S.Ve={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,256:a.O_NOCTTY,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY,131072:a.O_NOFOLLOW}},Nc(a){return S.createNode(null,"/",We(a.Nd.root),0)},createNode(a,b,c){if(!Q(c)&&!C.isFile(c)&&40960!==(c&61440))throw new C.Fc(28);a=C.createNode(a,b,c);a.Hc=S.Hc;a.Ic=S.Ic;return a},Hc:{$c(a){var b=Xe(a),c;R(()=>c=(void 0).Mf(b));S.je&&(c.wd||(c.wd=
4096),c.Dd||(c.Dd=(c.size+c.wd-1)/c.wd|0),c.mode|=(c.mode&292)>>2);return{fe:c.fe,Wd:c.Wd,mode:c.mode,ne:c.ne,uid:c.uid,ge:c.ge,yd:c.yd,size:c.size,ce:c.ce,le:c.le,de:c.de,wd:c.wd,Dd:c.Dd}},Tc(a,b){var c=Xe(a);R(()=>{if(void 0!==b.mode){var d=b.mode;S.je&&(d&=384);(void 0).lg(c,d);a.mode=b.mode}void 0!==b.timestamp&&(d=new Date(b.timestamp),(void 0).Ug(c,d,d));void 0!==b.size&&(void 0).Rg(c,b.size)})},sd(a,b){var c=Xe(a);c=xe(c+"/"+b);c=We(c);return S.createNode(a,b,c)},ed(a,b,c,d){var e=S.createNode(a,
b,c,d),f=Xe(e);R(()=>{Q(e.mode)?(void 0).Bg(f,e.mode):(void 0).Vg(f,"",{mode:e.mode})});return e},Ad(a,b,c){var d=Xe(a),e=Be(Xe(b),c);R(()=>(void 0).Mg(d,e));a.name=c},Bd(a,b){var c=Be(Xe(a),b);R(()=>(void 0).Sg(c))},vd(a,b){var c=Be(Xe(a),b);R(()=>(void 0).Ng(c))},zd(a){var b=Xe(a);return R(()=>(void 0).Ig(b))},hd(a,b,c){var d=Be(Xe(a),b);R(()=>(void 0).Pg(c,d))},ud(a){var b=Xe(a);return R(()=>(void 0).Jg(b))},Fe(a){var b=R(()=>(void 0).Og(a));b.zf=b.nf;return b}},Ic:{open(a){var b=Xe(a.node);R(()=>
{if(C.isFile(a.node.mode)){a.Jd.cf=1;var c=(void 0).Fg,d=a.flags;d&=-2721793;var e=0,f;for(f in S.Ve)d&f&&(e|=S.Ve[f],d^=f);if(d)throw new C.Fc(28);a.Zd=c.call(void 0,b,e)}})},close(a){R(()=>{C.isFile(a.node.mode)&&a.Zd&&0===--a.Jd.cf&&(void 0).mg(a.Zd)})},vf(a){a.Jd.cf++},read(a,b,c,d,e){return 0===d?0:R(()=>(void 0).Hg(a.Zd,new Int8Array(b.buffer,c,d),0,d,e))},write(a,b,c,d,e){return R(()=>(void 0).Wg(a.Zd,new Int8Array(b.buffer,c,d),0,d,e))},Vc(a,b,c){var d=b;1===c?d+=a.position:2===c&&C.isFile(a.node.mode)&&
R(()=>{var e=(void 0).tg(a.Zd);d+=e.size});if(0>d)throw new C.Fc(28);return d},xd(a,b,c){if(!C.isFile(a.node.mode))throw new C.Fc(43);var d=Oe(b);S.Ic.read(a,g(),d,b,c);return{Lc:d,se:!0}},Hd(a,b,c,d){S.Ic.write(a,b,0,d,c,!1);return 0}}},U={qe:16895,Rd:33279,De:null,Nc(a){function b(f){f=f.split("/");for(var h=d,k=0;k<f.length-1;k++){var l=f.slice(0,k+1).join("/");let n,m;(n=e)[m=l]||(n[m]=U.createNode(h,f[k],U.qe,0));h=e[l]}return h}function c(f){f=f.split("/");return f[f.length-1]}U.De??(U.De=new FileReaderSync);
var d=U.createNode(null,"/",U.qe,0),e={};Array.prototype.forEach.call(a.Nd.files||[],function(f){U.createNode(b(f.name),c(f.name),U.Rd,0,f,f.lastModifiedDate)});(a.Nd.blobs||[]).forEach(f=>{U.createNode(b(f.name),c(f.name),U.Rd,0,f.data)});(a.Nd.packages||[]).forEach(f=>{f.metadata.files.forEach(h=>{var k=h.filename.substr(1);U.createNode(b(k),c(k),U.Rd,0,f.blob.slice(h.start,h.end))})});return d},createNode(a,b,c,d,e,f){d=C.createNode(a,b,c);d.mode=c;d.Hc=U.Hc;d.Ic=U.Ic;d.timestamp=(f||new Date).getTime();
U.Rd!==U.qe||Va();c===U.Rd?(d.size=e.size,d.Jc=e):(d.size=4096,d.Jc={});a&&(a.Jc[b]=d);return d},Hc:{$c(a){return{fe:1,Wd:a.id,mode:a.mode,ne:1,uid:0,ge:0,yd:0,size:a.size,ce:new Date(a.timestamp),le:new Date(a.timestamp),de:new Date(a.timestamp),wd:4096,Dd:Math.ceil(a.size/4096)}},Tc(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp)},sd(){throw new C.Fc(44);},ed(){throw new C.Fc(63);},Ad(){throw new C.Fc(63);},Bd(){throw new C.Fc(63);},vd(){throw new C.Fc(63);
},zd(a){var b=[".",".."],c;for(c of Object.keys(a.Jc))b.push(c);return b},hd(){throw new C.Fc(63);}},Ic:{read(a,b,c,d,e){if(e>=a.node.size)return 0;a=a.node.Jc.slice(e,e+d);d=U.De.readAsArrayBuffer(a);b.set(new Uint8Array(d),c);return a.size},write(){throw new C.Fc(29);},Vc(a,b,c){1===c?b+=a.position:2===c&&C.isFile(a.node.mode)&&(b+=a.node.size);if(0>b)throw new C.Fc(28);return b}}};function Je(a,b){C.Re[a]={Ic:b}}function Q(a){return 16384===(a&61440)}
function Qe(a,b){var c=Q(a.mode)?(c=Ye(a,"x"))?c:a.Hc.sd?0:2:54;if(c)throw new C.Fc(c);for(c=C.kd[Ze(a.id,b)];c;c=c.Id){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return C.sd(a,b)}
function V(a,b={}){a=Ce(a);if(!a)return{path:"",node:null};b=Object.assign({ue:!0,Ee:0},b);if(8<b.Ee)throw new C.Fc(32);a=a.split("/").filter(h=>!!h);for(var c=C.root,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=Qe(c,a[e]);d=xe(d+"/"+a[e]);c.fd&&(!f||f&&b.ue)&&(c=c.fd.root);if(!f||b.Zc)for(f=0;40960===(c.mode&61440);)if(c=C.ud(d),d=Ce(ye(d),c),c=V(d,{Ee:b.Ee+1}).node,40<f++)throw new C.Fc(32);}return{path:d,node:c}}
function $e(a){for(var b;;){if(C.Ye(a))return a=a.Nc.$e,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Ze(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%C.kd.length}function af(a){var b=Ze(a.parent.id,a.name);a.Id=C.kd[b];C.kd[b]=a}function bf(a){var b=Ze(a.parent.id,a.name);if(C.kd[b]===a)C.kd[b]=a.Id;else for(b=C.kd[b];b;){if(b.Id===a){b.Id=a.Id;break}b=b.Id}}
function cf(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ye(a,b){if(C.ve)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function df(a,b){try{return Qe(a,b),20}catch(c){}return Ye(a,"wx")}function ef(a,b,c){try{var d=Qe(a,b)}catch(e){return e.Kc}if(a=Ye(a,"wx"))return a;if(c){if(!Q(d.mode))return 54;if(C.Ye(d)||$e(d)===C.ee())return 10}else if(Q(d.mode))return 31;return 0}
function W(a){a=C.We(a);if(!a)throw new C.Fc(8);return a}function ff(a,b=-1){a=Object.assign(new C.jf,a);if(-1==b)a:{for(b=0;b<=C.lf;b++)if(!C.streams[b])break a;throw new C.Fc(33);}a.Uc=b;return C.streams[b]=a}function gf(a,b=-1){a=ff(a,b);a.Ic?.vf?.(a);return a}function hf(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.Yd)}return b}function jf(a,b,c){"undefined"==typeof c&&(c=b,b=438);return C.ed(a,b|8192,c)}
function kf(a,b,c){a="string"==typeof a?V(a,{Zc:!c}).node:a;if(!a.Hc.Tc)throw new C.Fc(63);a.Hc.Tc(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}function lf(a,b){a="string"==typeof a?V(a,{Zc:!b}).node:a;if(!a.Hc.Tc)throw new C.Fc(63);a.Hc.Tc(a,{timestamp:Date.now()})}
function mf(){C.ad("/dev");Je(C.Gd(1,3),{read:()=>0,write:(d,e,f,h)=>h,Vc:()=>0});jf("/dev/null",C.Gd(1,3));Ie(C.Gd(5,0),Le);Ie(C.Gd(6,0),Me);jf("/dev/tty",C.Gd(5,0));jf("/dev/tty1",C.Gd(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=ve(a).byteLength);return a[--b]};C.Ed("/dev","random",c);C.Ed("/dev","urandom",c);C.ad("/dev/shm");C.ad("/dev/shm/tmp")}
function nf(){C.ad("/proc");var a=C.ad("/proc/self");C.ad("/proc/self/fd");C.Nc({Nc(){var b=C.createNode(a,"fd",16895,73);b.Hc={sd(c,d){var e=W(+d);c={parent:null,Nc:{$e:"fake"},Hc:{ud:()=>e.path}};return c.parent=c}};return b}},{},"/proc/self/fd")}function of(a,b,c,d){a="string"==typeof a?a:$e(a);b=xe(a+"/"+b);return C.create(b,Ue(c,d))}
function pf(a){if(!(a.xe||a.Lf||a.link||a.Jc)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.Jc=ta(a.url),a.Pc=a.Jc.length}catch(b){throw new C.Fc(29);}}}
var C={root:null,Yd:[],Re:{},streams:[],Ae:1,kd:null,Pe:"/",we:!1,ve:!0,Fc:class{name="ErrnoError";constructor(a){this.Kc=a}},yf:null,oe:0,jf:class{Jd={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Jd.flags}set flags(a){this.Jd.flags=a}get position(){return this.Jd.position}set position(a){this.Jd.position=a}},hf:class{Hc={};Ic={};fd=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Nc=a.Nc;this.id=C.Ae++;this.name=b;this.mode=c;this.yd=d}get read(){return 365===
(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Lf(){return Q(this.mode)}get xe(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new C.hf(a,b,c,d);af(a);return a},Ye(a){return a===a.parent},isFile(a){return 32768===(a&61440)},lf:4096,We:a=>C.streams[a],rf:{open(a){a.Ic=C.Bf(a.node.yd).Ic;a.Ic.open?.(a)},Vc(){throw new C.Fc(70);}},ze:a=>a>>8,Ag:a=>a&255,Gd:(a,b)=>a<<8|b,Bf:a=>C.Re[a],ff(a,
b){function c(h){C.oe--;return b(h)}function d(h){if(h){if(!d.wf)return d.wf=!0,c(h)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);C.oe++;1<C.oe&&B(`warning: ${C.oe} FS.syncfs operations in flight at once, probably just doing extra work`);var e=hf(C.root.Nc),f=0;e.forEach(h=>{if(!h.type.ff)return d(null);h.type.ff(h,a,d)})},Nc(a,b,c){var d="/"===c;if(d&&C.root)throw new C.Fc(10);if(!d&&c){var e=V(c,{ue:!1});c=e.path;e=e.node;if(e.fd)throw new C.Fc(10);if(!Q(e.mode))throw new C.Fc(54);
}b={type:a,Nd:b,$e:c,Yd:[]};a=a.Nc(b);a.Nc=b;b.root=a;d?C.root=a:e&&(e.fd=b,e.Nc&&e.Nc.Yd.push(b));return a},Tg(a){a=V(a,{ue:!1});if(!a.node.fd)throw new C.Fc(28);a=a.node;var b=a.fd,c=hf(b);Object.keys(C.kd).forEach(d=>{for(d=C.kd[d];d;){var e=d.Id;c.includes(d.Nc)&&bf(d);d=e}});a.fd=null;a.Nc.Yd.splice(a.Nc.Yd.indexOf(b),1)},sd(a,b){return a.Hc.sd(a,b)},ed(a,b,c){var d=V(a,{parent:!0}).node;a=ze(a);if(!a||"."===a||".."===a)throw new C.Fc(28);var e=df(d,a);if(e)throw new C.Fc(e);if(!d.Hc.ed)throw new C.Fc(63);
return d.Hc.ed(d,a,b,c)},Fe(a){var b={nf:4096,zf:4096,Dd:1E6,eg:5E5,dg:5E5,files:C.Ae,qg:C.Ae-1,sg:42,flags:2,Dg:255};a=V(a,{Zc:!0}).node;a?.Hc.Fe&&Object.assign(b,a.Hc.Fe(a.Nc.Nd.root));return b},create(a,b=438){return C.ed(a,b&4095|32768,0)},ad(a,b=511){return C.ed(a,b&1023|16384,0)},Cg(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{C.ad(c,b)}catch(e){if(20!=e.Kc)throw e;}}},hd(a,b){if(!Ce(a))throw new C.Fc(44);var c=V(b,{parent:!0}).node;if(!c)throw new C.Fc(44);b=
ze(b);var d=df(c,b);if(d)throw new C.Fc(d);if(!c.Hc.hd)throw new C.Fc(63);return c.Hc.hd(c,b,a)},Ad(a,b){var c=ye(a),d=ye(b),e=ze(a),f=ze(b);var h=V(a,{parent:!0});var k=h.node;h=V(b,{parent:!0});h=h.node;if(!k||!h)throw new C.Fc(44);if(k.Nc!==h.Nc)throw new C.Fc(75);var l=Qe(k,e);a=De(a,d);if("."!==a.charAt(0))throw new C.Fc(28);a=De(b,c);if("."!==a.charAt(0))throw new C.Fc(55);try{var n=Qe(h,f)}catch(m){}if(l!==n){b=Q(l.mode);if(e=ef(k,e,b))throw new C.Fc(e);if(e=n?ef(h,f,b):df(h,f))throw new C.Fc(e);
if(!k.Hc.Ad)throw new C.Fc(63);if(l.fd||n&&n.fd)throw new C.Fc(10);if(h!==k&&(e=Ye(k,"w")))throw new C.Fc(e);bf(l);try{k.Hc.Ad(l,h,f),l.parent=h}catch(m){throw m;}finally{af(l)}}},vd(a){var b=V(a,{parent:!0}).node;a=ze(a);var c=Qe(b,a),d=ef(b,a,!0);if(d)throw new C.Fc(d);if(!b.Hc.vd)throw new C.Fc(63);if(c.fd)throw new C.Fc(10);b.Hc.vd(b,a);bf(c)},zd(a){a=V(a,{Zc:!0}).node;if(!a.Hc.zd)throw new C.Fc(54);return a.Hc.zd(a)},Bd(a){var b=V(a,{parent:!0}).node;if(!b)throw new C.Fc(44);a=ze(a);var c=Qe(b,
a),d=ef(b,a,!1);if(d)throw new C.Fc(d);if(!b.Hc.Bd)throw new C.Fc(63);if(c.fd)throw new C.Fc(10);b.Hc.Bd(b,a);bf(c)},ud(a){a=V(a).node;if(!a)throw new C.Fc(44);if(!a.Hc.ud)throw new C.Fc(28);return a.Hc.ud(a)},stat(a,b){a=V(a,{Zc:!b}).node;if(!a)throw new C.Fc(44);if(!a.Hc.$c)throw new C.Fc(63);return a.Hc.$c(a)},Ze(a){return C.stat(a,!0)},yg(a,b){kf(a,b,!0)},zg(a){lf(a,!0)},pg(a){a=W(a);lf(a.node)},truncate(a,b){if(0>b)throw new C.Fc(28);a="string"==typeof a?V(a,{Zc:!0}).node:a;if(!a.Hc.Tc)throw new C.Fc(63);
if(Q(a.mode))throw new C.Fc(31);if(!C.isFile(a.mode))throw new C.Fc(28);var c=Ye(a,"w");if(c)throw new C.Fc(c);a.Hc.Tc(a,{size:b,timestamp:Date.now()})},ug(a,b){a=W(a);if(0===(a.flags&2097155))throw new C.Fc(28);C.truncate(a.node,b)},open(a,b,c=438){if(""===a)throw new C.Fc(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)var e=a;else{a=xe(a);try{e=V(a,
{Zc:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new C.Fc(20);}else e=C.ed(a,c,0),d=!0;if(!e)throw new C.Fc(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!Q(e.mode))throw new C.Fc(54);if(!d&&(a=e?40960===(e.mode&61440)?32:Q(e.mode)&&("r"!==cf(b)||b&512)?31:Ye(e,cf(b)):44))throw new C.Fc(a);b&512&&!d&&C.truncate(e,0);b&=-131713;e=ff({node:e,path:$e(e),flags:b,seekable:!0,position:0,Ic:e.Ic,Yf:[],error:!1});e.Ic.open&&e.Ic.open(e);return e},close(a){if(null===a.Uc)throw new C.Fc(8);
a.Fd&&(a.Fd=null);try{a.Ic.close&&a.Ic.close(a)}catch(b){throw b;}finally{C.streams[a.Uc]=null}a.Uc=null},Vc(a,b,c){if(null===a.Uc)throw new C.Fc(8);if(!a.seekable||!a.Ic.Vc)throw new C.Fc(70);if(0!=c&&1!=c&&2!=c)throw new C.Fc(28);a.position=a.Ic.Vc(a,b,c);a.Yf=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new C.Fc(28);if(null===a.Uc)throw new C.Fc(8);if(1===(a.flags&2097155))throw new C.Fc(8);if(Q(a.node.mode))throw new C.Fc(31);if(!a.Ic.read)throw new C.Fc(28);var f="undefined"!=typeof e;
if(!f)e=a.position;else if(!a.seekable)throw new C.Fc(70);b=a.Ic.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new C.Fc(28);if(null===a.Uc)throw new C.Fc(8);if(0===(a.flags&2097155))throw new C.Fc(8);if(Q(a.node.mode))throw new C.Fc(31);if(!a.Ic.write)throw new C.Fc(28);a.seekable&&a.flags&1024&&C.Vc(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new C.Fc(70);b=a.Ic.write(a,b,c,d,e,f);h||(a.position+=b);return b},Kd(a,b,c){if(null===
a.Uc)throw new C.Fc(8);if(0>b||0>=c)throw new C.Fc(28);if(0===(a.flags&2097155))throw new C.Fc(8);if(!C.isFile(a.node.mode)&&!Q(a.node.mode))throw new C.Fc(43);if(!a.Ic.Kd)throw new C.Fc(138);a.Ic.Kd(a,b,c)},xd(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new C.Fc(2);if(1===(a.flags&2097155))throw new C.Fc(2);if(!a.Ic.xd)throw new C.Fc(43);if(!b)throw new C.Fc(28);return a.Ic.xd(a,b,c,d,e)},Hd(a,b,c,d,e){return a.Ic.Hd?a.Ic.Hd(a,b,c,d,e):0},Md(a,b,c){if(!a.Ic.Md)throw new C.Fc(59);
return a.Ic.Md(a,b,c)},Pf(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=C.open(a,b.flags);a=C.stat(a).size;var e=new Uint8Array(a);C.read(d,e,0,a,0);"utf8"===b.encoding?c=ge(e):"binary"===b.encoding&&(c=e);C.close(d);return c},cg(a,b,c={}){c.flags=c.flags||577;a=C.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(Fe(b)+1);b=Ge(b,d,0,d.length);C.write(a,d,0,b,void 0,
c.pf)}else if(ArrayBuffer.isView(b))C.write(a,b,0,b.byteLength,void 0,c.pf);else throw Error("Unsupported data type");C.close(a)},ee:()=>C.Pe,qf(a){a=V(a,{Zc:!0});if(null===a.node)throw new C.Fc(44);if(!Q(a.node.mode))throw new C.Fc(54);var b=Ye(a.node,"x");if(b)throw new C.Fc(b);C.Pe=a.path},ef(){C.kd=Array(4096);C.Nc(P,{},"/");C.ad("/tmp");C.ad("/home");C.ad("/home/web_user");mf();nf();C.yf={MEMFS:P,NODEFS:S,WORKERFS:U}},Vd(a,b,c){C.we=!0;a?C.Ed("/dev","stdin",a):C.hd("/dev/tty","/dev/stdin");b?
C.Ed("/dev","stdout",null,b):C.hd("/dev/tty","/dev/stdout");c?C.Ed("/dev","stderr",null,c):C.hd("/dev/tty1","/dev/stderr");C.open("/dev/stdin",0);C.open("/dev/stdout",1);C.open("/dev/stderr",1)},Gg(){C.we=!1;for(var a=0;a<C.streams.length;a++){var b=C.streams[a];b&&C.close(b)}},rg(a,b){try{var c=V(a,{Zc:!b});a=c.path}catch(f){}var d=!1,e=null;try{c=V(a,{parent:!0}),ze(a),c=V(a,{Zc:!b}),d=!0,e=c.node}catch(f){}return d?e:null},ng(a,b){a="string"==typeof a?a:$e(a);for(b=b.split("/").reverse();b.length;){var c=
b.pop();if(c){var d=xe(a+"/"+c);try{C.ad(d)}catch(e){}a=d}}return d},Ed(a,b,c,d){a=Be("string"==typeof a?a:$e(a),b);b=Ue(!!c,!!d);var e;(e=C.Ed).ze??(e.ze=64);e=C.Gd(C.Ed.ze++,0);Je(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,h,k,l){for(var n=0,m=0;m<l;m++){try{var r=c()}catch(x){throw new C.Fc(29);}if(void 0===r&&0===n)throw new C.Fc(6);if(null===r||void 0===r)break;n++;h[k+m]=r}n&&(f.node.timestamp=Date.now());return n},write(f,h,k,l){for(var n=0;n<l;n++)try{d(h[k+n])}catch(m){throw new C.Fc(29);
}l&&(f.node.timestamp=Date.now());return n}});return jf(a,b,e)},tf(a,b,c,d,e){function f(m,r,x,D,v){m=m.node.Jc;if(v>=m.length)return 0;D=Math.min(m.length-v,D);if(m.slice)for(var y=0;y<D;y++)r[x+y]=m[v+y];else for(y=0;y<D;y++)r[x+y]=m.get(v+y);return D}class h{re=!1;Cd=[];Ud=void 0;He=0;Ge=0;get(m){if(!(m>this.length-1||0>m)){var r=m%this.Je;return this.Ud(m/this.Je|0)[r]}}kf(m){this.Ud=m}Ie(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+
c+". Status: "+m.status);var r=Number(m.getResponseHeader("Content-length")),x,D=(x=m.getResponseHeader("Accept-Ranges"))&&"bytes"===x;m=(x=m.getResponseHeader("Content-Encoding"))&&"gzip"===x;var v=1048576;D||(v=r);var y=this;y.kf(L=>{var J=L*v,K=(L+1)*v-1;K=Math.min(K,r-1);if("undefined"==typeof y.Cd[L]){var ma=y.Cd;if(J>K)throw Error("invalid range ("+J+", "+K+") or no bytes requested!");if(K>r-1)throw Error("only "+r+" bytes available! programmer error!");var T=new XMLHttpRequest;T.open("GET",
c,!1);r!==v&&T.setRequestHeader("Range","bytes="+J+"-"+K);T.responseType="arraybuffer";T.overrideMimeType&&T.overrideMimeType("text/plain; charset=x-user-defined");T.send(null);if(!(200<=T.status&&300>T.status||304===T.status))throw Error("Couldn't load "+c+". Status: "+T.status);void 0!==T.response?J=new Uint8Array(T.response||[]):(K=T.responseText||"",J=Array(Fe(K)+1),K=Ge(K,J,0,J.length),J.length=K);ma[L]=J}if("undefined"==typeof y.Cd[L])throw Error("doXHR failed!");return y.Cd[L]});if(m||!r)v=
r=1,v=r=this.Ud(0).length,ua("LazyFiles on gzip forces download of the whole file when length is accessed");this.He=r;this.Ge=v;this.re=!0}get length(){this.re||this.Ie();return this.He}get Je(){this.re||this.Ie();return this.Ge}}var k="undefined"!=typeof XMLHttpRequest?{xe:!1,Jc:new h}:{xe:!1,url:c},l=of(a,b,d,e);k.Jc?l.Jc=k.Jc:k.url&&(l.Jc=null,l.url=k.url);Object.defineProperties(l,{Pc:{get:function(){return this.Jc.length}}});var n={};Object.keys(l.Ic).forEach(m=>{var r=l.Ic[m];n[m]=(...x)=>{pf(l);
return r(...x)}});n.read=(m,r,x,D,v)=>{pf(l);return f(m,r,x,D,v)};n.xd=(m,r,x)=>{pf(l);var D=Oe(r);if(!D)throw new C.Fc(48);f(m,g(),D,r,x);return{Lc:D,se:!0}};l.Ic=n;return l}};
function qf(a,b){if(1===a.type&&a.pd)throw new C.Fc(53);var c=a.Od.shift();if(!c){if(1===a.type){a=a.md[a.qd+":"+a.rd];if(!a)throw new C.Fc(53);if(a.Mc.readyState===a.Mc.CLOSING||a.Mc.readyState===a.Mc.CLOSED)return null}throw new C.Fc(6);}var d=c.data.byteLength||c.data.length,e=c.data.byteOffset||0,f=c.data.buffer||c.data;b=Math.min(b,d);var h={buffer:new Uint8Array(f,e,b),Sc:c.Sc,port:c.port};1===a.type&&b<d&&(c.data=new Uint8Array(f,e+b,d-b),a.Od.unshift(c));return h}
function rf(a,b,c,d,e,f){if(2===a.type){if(void 0===e||void 0===f)e=a.qd,f=a.rd;if(void 0===e||void 0===f)throw new C.Fc(17);}else e=a.qd,f=a.rd;var h=a.md[e+":"+f];if(1===a.type&&(!h||h.Mc.readyState===h.Mc.CLOSING||h.Mc.readyState===h.Mc.CLOSED))throw new C.Fc(53);ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);b=b.slice(c,c+d);b instanceof SharedArrayBuffer&&(b=(new Uint8Array(new Uint8Array(b))).buffer);if(!h||h.Mc.readyState!==h.Mc.OPEN)return 2===a.type&&(h&&h.Mc.readyState!==h.Mc.CLOSING&&
h.Mc.readyState!==h.Mc.CLOSED||(h=sf(a,e,f))),h.ke.push(b),d;try{return h.Mc.send(b),d}catch(k){throw new C.Fc(28);}}
function tf(a,b){var c=!0;b.Mc.onopen=function(){a.Oe=!1;Pa.Sd.open?.(a.stream.Uc);try{for(var d=b.ke.shift();d;)b.Mc.send(d),d=b.ke.shift()}catch(e){b.Mc.close()}};b.Mc.onclose=function(){Pa.Sd.close?.(a.stream.Uc)};b.Mc.onmessage=function(d){a:{d=d.data;if("string"==typeof d)d=(new TextEncoder).encode(d);else{void 0!==d.byteLength||Va();if(0==d.byteLength)break a;d=new Uint8Array(d)}var e=c;c=!1;e&&10===d.length&&255===d[0]&&255===d[1]&&255===d[2]&&255===d[3]&&112===d[4]&&111===d[5]&&114===d[6]&&
116===d[7]?(d=d[8]<<8|d[9],delete a.md[b.Sc+":"+b.port],b.port=d,a.md[b.Sc+":"+b.port]=b):(a.Od.push({Sc:b.Sc,port:b.port,data:d}),Pa.Sd.message?.(a.stream.Uc))}};b.Mc.onerror=function(){a.error=14;var d=[a.stream.Uc,a.error,"ECONNREFUSED: Connection refused"];Pa.Sd.error?.(d)}}
function sf(a,b,c){if("object"==typeof b){var d=b;c=b=null}if(d)if(d.Le)b=d.Le.Kg,c=d.Le.Lg;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var e="ws://",f="binary",h=void 0;if("ws://"===e||"wss://"===e){var k=b.split("/");e=e+k[0]+":"+c+"/"+k.slice(1).join("/")}"null"!==f&&(h=f=f.replace(/^ +| +$/g,"").split(/ *, */));d=new WebSocket(e,h);d.binaryType="arraybuffer"}catch(l){throw new C.Fc(23);
}b={Sc:b,port:c,Mc:d,ke:[]};a.md[b.Sc+":"+b.port]=b;tf(a,b);2===a.type&&"undefined"!=typeof a.ae&&b.ke.push(new Uint8Array([255,255,255,255,112,111,114,116,(a.ae&65280)>>8,a.ae&255]));return b}
var Pa={Sd:{},Eg(a,b){Pa.Sd[a]=b},Nc(){return C.createNode(null,"/",16895,0)},Ic:{af(a){a=a.node.Pd;return a.Qd.af(a)},Md(a,b,c){a=a.node.Pd;return a.Qd.Md(a,b,c)},read(a,b,c,d){a=qf(a.node.Pd,d);if(!a)return 0;b.set(a.buffer,c);return a.buffer.length},write(a,b,c,d){return rf(a.node.Pd,b,c,d)},close(a){a=a.node.Pd;a.Qd.close(a)}},me(){Pa.me.current||(Pa.me.current=0);return`socket[${Pa.me.current++}]`},bg:{af(a){if(1===a.type&&a.pd)return a.pending.length?65:0;var b=0,c=1===a.type?a.md[a.qd+":"+
a.rd]:null;if(a.Od.length||!c||c&&c.Mc.readyState===c.Mc.CLOSING||c&&c.Mc.readyState===c.Mc.CLOSED)b|=65;if(!c||c&&c.Mc.readyState===c.Mc.OPEN)b|=4;if(c&&c.Mc.readyState===c.Mc.CLOSING||c&&c.Mc.readyState===c.Mc.CLOSED)b=a.Oe?b|4:b|16;return b},Md(a,b,c){switch(b){case 21531:return b=0,a.Od.length&&(b=a.Od[0].data.length),u()[c>>2]=b,0;default:return 28}},close(a){if(a.pd){try{a.pd.close()}catch(e){}a.pd=null}for(var b=Object.keys(a.md),c=0;c<b.length;c++){var d=a.md[b[c]];try{d.Mc.close()}catch(e){}delete a.md[d.Sc+
":"+d.port]}return 0},bind(a,b,c){if("undefined"!=typeof a.df||"undefined"!=typeof a.ae)throw new C.Fc(28);a.df=b;a.ae=c;if(2===a.type){a.pd&&(a.pd.close(),a.pd=null);try{throw new C.Fc(138);}catch(d){if("ErrnoError"!==d.name)throw d;if(138!==d.Kc)throw d;}}},connect(a,b,c){if(a.pd)throw new C.Fc(138);if("undefined"!=typeof a.qd&&"undefined"!=typeof a.rd){var d=a.md[a.qd+":"+a.rd];if(d){if(d.Mc.readyState===d.Mc.CONNECTING)throw new C.Fc(7);throw new C.Fc(30);}}b=sf(a,b,c);a.qd=b.Sc;a.rd=b.port;a.Oe=
!0},accept(a){if(!a.pd||!a.pending.length)throw new C.Fc(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},wg(a,b){if(b){if(void 0===a.qd||void 0===a.rd)throw new C.Fc(53);b=a.qd;a=a.rd}else b=a.df||0,a=a.ae||0;return{Sc:b,port:a}}}},uf=a=>{a=(a=C.We(a))&&49152===(a.node.mode&49152)?a.node.Pd:null;if(!a)throw new C.Fc(8);return a},vf=a=>{a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0},xf=a=>{var b,
c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-1]),a=a.slice(0,
a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"==typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=wf(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]},yf=(a,b,c,d,e)=>{switch(b){case 2:c=vf(c);q().fill(0,a,a+16);e&&(u()[e>>2]=16);t()[a>>1]=b;u()[a+4>>2]=c;t()[a+2>>1]=wf(d);break;case 10:c=xf(c);q().fill(0,a,a+28);e&&(u()[e>>2]=28);u()[a>>2]=b;u()[a+8>>2]=c[0];u()[a+12>>2]=c[1];u()[a+16>>2]=c[2];u()[a+
20>>2]=c[3];t()[a+2>>1]=wf(d);break;default:return 5}return 0},zf=1,Af={},Bf={};function Cf(a){var b=vf(a);if(null!==b)return a;b=xf(a);if(null!==b)return a;Af[a]?b=Af[a]:(b=zf++,65535>b||Va("exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),Bf[b]=a,Af[a]=b);return b}
function ob(a,b,c,d,e,f){if(A)return I(3,1,a,b,c,d,e,f);try{var h=uf(a),k=h.Qd.accept(h);b&&yf(b,k.family,Cf(k.qd),k.rd,c);return k.stream.Uc}catch(l){if("undefined"==typeof C||"ErrnoError"!==l.name)throw l;return-l.Kc}}
var Df=a=>(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255),Ff=a=>{var b="",c,d=0,e=0,f=0,h=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var k=!0;for(c=0;5>c;c++)if(0!==a[c]){k=!1;break}if(k){c=Df(a[6]|a[7]<<16);if(-1===a[5])return"::ffff:"+c;if(0===a[5])return"0.0.0.0"===c&&(c=""),"0.0.0.1"===c&&(c="1"),"::"+c}for(c=0;8>c;c++)0===a[c]&&(1<c-e&&(h=0),e=c,h++),h>d&&(d=h,f=c-d+1);for(c=0;8>c;c++)1<d&&0===a[c]&&c>=f&&c<f+d?c===f&&(b+=":",0===f&&(b+=":")):
(b+=Number(Ef(a[c]&65535)).toString(16),b+=7>c?":":"");return b},Gf=(a,b)=>{var c=t()[a>>1],d=Ef(ea()[a+2>>1]);switch(c){case 2:if(16!==b)return{Kc:28};a=u()[a+4>>2];a=Df(a);break;case 10:if(28!==b)return{Kc:28};a=[u()[a+8>>2],u()[a+12>>2],u()[a+16>>2],u()[a+20>>2]];a=Ff(a);break;default:return{Kc:5}}return{family:c,Sc:a,port:d}},Hf=(a,b)=>{a=Gf(a,b);if(a.Kc)throw new C.Fc(a.Kc);b=a.Sc;a.Sc=(Bf[b]?Bf[b]:null)||a.Sc;return a};
function pb(a,b,c,d,e,f){if(A)return I(4,1,a,b,c,d,e,f);try{var h=uf(a),k=Hf(b,c);h.Qd.bind(h,k.Sc,k.port);return 0}catch(l){if("undefined"==typeof C||"ErrnoError"!==l.name)throw l;return-l.Kc}}function If(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?C.ee():W(a).path;if(0==b.length){if(!c)throw new C.Fc(44);return a}return xe(a+"/"+b)}
function Jf(a,b,c){a=a(b);u()[c>>2]=a.fe;u()[c+4>>2]=a.mode;w()[c+8>>2]=a.ne;u()[c+12>>2]=a.uid;u()[c+16>>2]=a.ge;u()[c+20>>2]=a.yd;F=[a.size>>>0,(E=a.size,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];u()[c+24>>2]=F[0];u()[c+28>>2]=F[1];u()[c+32>>2]=4096;u()[c+36>>2]=a.Dd;b=a.ce.getTime();var d=a.le.getTime(),e=a.de.getTime();F=[Math.floor(b/1E3)>>>0,(E=Math.floor(b/1E3),1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>
0))/4294967296)>>>0:0)];u()[c+40>>2]=F[0];u()[c+44>>2]=F[1];w()[c+48>>2]=b%1E3*1E6;F=[Math.floor(d/1E3)>>>0,(E=Math.floor(d/1E3),1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];u()[c+56>>2]=F[0];u()[c+60>>2]=F[1];w()[c+64>>2]=d%1E3*1E6;F=[Math.floor(e/1E3)>>>0,(E=Math.floor(e/1E3),1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];u()[c+72>>2]=F[0];u()[c+76>>2]=F[1];w()[c+80>>2]=e%1E3*1E6;F=[a.Wd>>>0,
(E=a.Wd,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];u()[c+88>>2]=F[0];u()[c+92>>2]=F[1];return 0}var Kf=void 0;function qb(a,b){if(A)return I(5,1,a,b);try{return a=N(a),kf(a,b),0}catch(c){if("undefined"==typeof C||"ErrnoError"!==c.name)throw c;return-c.Kc}}
function rb(a,b,c,d,e,f){if(A)return I(6,1,a,b,c,d,e,f);try{var h=uf(a),k=Hf(b,c);h.Qd.connect(h,k.Sc,k.port);return 0}catch(l){if("undefined"==typeof C||"ErrnoError"!==l.name)throw l;return-l.Kc}}function sb(a){if(A)return I(7,1,a);try{var b=W(a);return gf(b).Uc}catch(c){if("undefined"==typeof C||"ErrnoError"!==c.name)throw c;return-c.Kc}}
function tb(a,b,c,d){if(A)return I(8,1,a,b,c,d);try{b=N(b);b=If(a,b);if(c&-8)return-28;var e=V(b,{Zc:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Ye(e,a)?-2:0}catch(f){if("undefined"==typeof C||"ErrnoError"!==f.name)throw f;return-f.Kc}}function ub(a,b,c,d,e,f){if(A)return I(9,1,a,b,c,d,e,f);b=Td(c,d);e=Td(e,f);try{if(isNaN(b))return 61;var h=W(a);C.Kd(h,b,e);return 0}catch(k){if("undefined"==typeof C||"ErrnoError"!==k.name)throw k;return-k.Kc}}
function vb(a,b){if(A)return I(10,1,a,b);try{var c=W(a);kf(c.node,b);return 0}catch(d){if("undefined"==typeof C||"ErrnoError"!==d.name)throw d;return-d.Kc}}var Lf=()=>{var a=u()[+Kf>>2];Kf+=4;return a};
function wb(a,b,c){if(A)return I(11,1,a,b,c);Kf=c;try{var d=W(a);switch(b){case 0:var e=Lf();if(0>e)break;for(;C.streams[e];)e++;return gf(d,e).Uc;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Lf(),d.flags|=e,0;case 12:return e=Lf(),t()[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof C||"ErrnoError"!==f.name)throw f;return-f.Kc}}
function xb(a,b){if(A)return I(12,1,a,b);try{var c=W(a);return Jf(C.stat,c.path,b)}catch(d){if("undefined"==typeof C||"ErrnoError"!==d.name)throw d;return-d.Kc}}var Mf=(a,b)=>{Ge(a,q(),b,17)};function yb(a,b){if(A)return I(13,1,a,b);try{if(0===b)return-28;var c=C.ee(),d=Fe(c)+1;if(b<d)return-68;Ge(c,q(),a,b);return d}catch(e){if("undefined"==typeof C||"ErrnoError"!==e.name)throw e;return-e.Kc}}
function zb(a,b,c){if(A)return I(14,1,a,b,c);try{var d=W(a);d.Fd||(d.Fd=C.zd(d.path));a=0;for(var e=C.Vc(d,0,1),f=Math.floor(e/280);f<d.Fd.length&&a+280<=c;){var h=d.Fd[f];if("."===h){var k=d.node.id;var l=4}else if(".."===h)k=V(d.path,{parent:!0}).node.id,l=4;else{var n=Qe(d.node,h);k=n.id;l=8192===(n.mode&61440)?2:Q(n.mode)?4:40960===(n.mode&61440)?10:8}F=[k>>>0,(E=k,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];u()[b+a>>2]=F[0];u()[b+a+4>>2]=
F[1];F=[280*(f+1)>>>0,(E=280*(f+1),1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];u()[b+a+8>>2]=F[0];u()[b+a+12>>2]=F[1];t()[b+a+16>>1]=280;g()[b+a+18]=l;e=b+a+19;Ge(h,q(),e,256);a+=280;f+=1}C.Vc(d,280*f,0);return a}catch(m){if("undefined"==typeof C||"ErrnoError"!==m.name)throw m;return-m.Kc}}
function Ab(a,b,c){if(A)return I(15,1,a,b,c);Kf=c;try{var d=W(a);switch(b){case 21509:return d.Oc?0:-59;case 21505:if(!d.Oc)return-59;if(d.Oc.td.If){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Lf();u()[e>>2]=25856;u()[e+4>>2]=5;u()[e+8>>2]=191;u()[e+12>>2]=35387;for(var f=0;32>f;f++)g()[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Oc?0:-59;case 21506:case 21507:case 21508:if(!d.Oc)return-59;if(d.Oc.td.Jf)for(e=Lf(),u(),u(),u(),u(),a=[],
f=0;32>f;f++)a.push(g()[e+f+17]);return 0;case 21519:if(!d.Oc)return-59;e=Lf();return u()[e>>2]=0;case 21520:return d.Oc?-28:-59;case 21531:return e=Lf(),C.Md(d,b,e);case 21523:if(!d.Oc)return-59;d.Oc.td.Kf&&(f=[24,80],e=Lf(),t()[e>>1]=f[0],t()[e+2>>1]=f[1]);return 0;case 21524:return d.Oc?0:-59;case 21515:return d.Oc?0:-59;default:return-28}}catch(h){if("undefined"==typeof C||"ErrnoError"!==h.name)throw h;return-h.Kc}}
function Bb(a,b){if(A)return I(16,1,a,b);try{throw uf(a),new C.Fc(138);}catch(c){if("undefined"==typeof C||"ErrnoError"!==c.name)throw c;return-c.Kc}}function Cb(a,b){if(A)return I(17,1,a,b);try{return a=N(a),Jf(C.Ze,a,b)}catch(c){if("undefined"==typeof C||"ErrnoError"!==c.name)throw c;return-c.Kc}}function Db(a,b,c,d){if(A)return I(18,1,a,b,c,d);try{b=N(b);var e=d&256;b=If(a,b,d&4096);return Jf(e?C.Ze:C.stat,b,c)}catch(f){if("undefined"==typeof C||"ErrnoError"!==f.name)throw f;return-f.Kc}}
function Eb(a,b,c,d){if(A)return I(19,1,a,b,c,d);Kf=d;try{b=N(b);b=If(a,b);var e=d?Lf():0;return C.open(b,c,e).Uc}catch(f){if("undefined"==typeof C||"ErrnoError"!==f.name)throw f;return-f.Kc}}function Fb(a,b,c,d){if(A)return I(20,1,a,b,c,d);try{b=N(b);b=If(a,b);if(0>=d)return-28;var e=C.ud(b),f=Math.min(d,Fe(e)),h=g()[c+f];a=d+1;Ge(e,q(),c,a);g()[c+f]=h;return f}catch(k){if("undefined"==typeof C||"ErrnoError"!==k.name)throw k;return-k.Kc}}
function Gb(a,b,c,d,e,f){if(A)return I(21,1,a,b,c,d,e,f);try{var h=uf(a),k=qf(h,c);if(!k)return 0;e&&yf(e,h.family,Cf(k.Sc),k.port,f);q().set(k.buffer,b);return k.buffer.byteLength}catch(l){if("undefined"==typeof C||"ErrnoError"!==l.name)throw l;return-l.Kc}}function Hb(a,b,c,d){if(A)return I(22,1,a,b,c,d);try{return b=N(b),d=N(d),b=If(a,b),d=If(c,d),C.Ad(b,d),0}catch(e){if("undefined"==typeof C||"ErrnoError"!==e.name)throw e;return-e.Kc}}
function Ib(a){if(A)return I(23,1,a);try{return a=N(a),C.vd(a),0}catch(b){if("undefined"==typeof C||"ErrnoError"!==b.name)throw b;return-b.Kc}}function Jb(a,b,c,d,e,f){if(A)return I(24,1,a,b,c,d,e,f);try{var h=uf(a);if(!e)return C.write(h.stream,g(),b,c);var k=Hf(e,f);return rf(h,g(),b,c,k.Sc,k.port)}catch(l){if("undefined"==typeof C||"ErrnoError"!==l.name)throw l;return-l.Kc}}
function Kb(a,b,c){if(A)return I(25,1,a,b,c);try{b&=-526337;if(1==b&&c&&6!=c)throw new C.Fc(66);var d={family:a,type:b,protocol:c,pd:null,error:null,md:{},pending:[],Od:[],Qd:Pa.bg},e=Pa.me(),f=C.createNode(Pa.root,e,49152,0);f.Pd=d;var h=ff({path:e,node:f,flags:2,seekable:!1,Ic:Pa.Ic});d.stream=h;return d.stream.Uc}catch(k){if("undefined"==typeof C||"ErrnoError"!==k.name)throw k;return-k.Kc}}
function Lb(a,b){if(A)return I(26,1,a,b);try{return a=N(a),Jf(C.stat,a,b)}catch(c){if("undefined"==typeof C||"ErrnoError"!==c.name)throw c;return-c.Kc}}function Mb(a,b,c){if(A)return I(27,1,a,b,c);try{return a=N(a),c=N(c),c=If(b,c),C.hd(a,c),0}catch(d){if("undefined"==typeof C||"ErrnoError"!==d.name)throw d;return-d.Kc}}
function Nb(a,b,c){if(A)return I(28,1,a,b,c);try{return b=N(b),b=If(a,b),0===c?C.Bd(b):512===c?C.vd(b):Va("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof C||"ErrnoError"!==d.name)throw d;return-d.Kc}}var Nf=a=>w()[a>>2]+4294967296*u()[a+4>>2];
function Ob(a,b,c,d){if(A)return I(29,1,a,b,c,d);try{b=N(b);b=If(a,b,!0);var e=Date.now();if(c){var f=Nf(c),h=u()[c+8>>2];var k=1073741823==h?e:1073741822==h?-1:1E3*f+h/1E6;c+=16;f=Nf(c);h=u()[c+8>>2];var l=1073741823==h?e:1073741822==h?-1:1E3*f+h/1E6}else l=k=e;if(-1!=l||-1!=k){a=k;var n=V(b,{Zc:!0}).node;n.Hc.Tc(n,{timestamp:Math.max(a,l)})}return 0}catch(m){if("undefined"==typeof C||"ErrnoError"!==m.name)throw m;return-m.Kc}}var Pb=()=>Va(""),Of={},Pf=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Qf(a){return this.fromWireType(w()[a>>2])}
var Rf={},Sf={},Tf={},Uf,Wf=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new Uf("Mismatched type converter count");for(var l=0;l<a.length;++l)Vf(a[l],k[l])}a.forEach(k=>Tf[k]=b);var e=Array(b.length),f=[],h=0;b.forEach((k,l)=>{Sf.hasOwnProperty(k)?e[l]=Sf[k]:(f.push(k),Rf.hasOwnProperty(k)||(Rf[k]=[]),Rf[k].push(()=>{e[l]=Sf[k];++h;h===f.length&&d(e)}))});0===f.length&&d(e)},Qb=a=>{var b=Of[a];delete Of[a];var c=b.Ce,d=b.od,e=b.Ue,f=e.map(h=>h.Ef).concat(e.map(h=>h.Rf));Wf([a],f,h=>
{var k={};e.forEach((l,n)=>{var m=h[n],r=l.Ud,x=l.Df,D=h[n+e.length],v=l.Qf,y=l.Sf;k[l.xf]={read:L=>m.fromWireType(r(x,L)),write:(L,J)=>{var K=[];v(y,L,D.toWireType(K,J));Pf(K)}}});return[{name:b.name,fromWireType:l=>{var n={},m;for(m in k)n[m]=k[m].read(l);d(l);return n},toWireType:(l,n)=>{for(var m in k)if(!(m in n))throw new TypeError(`Missing field: "${m}"`);var r=c();for(m in k)k[m].write(r,n[m]);null!==l&&l.push(d,r);return r},cd:Xf,readValueFromPointer:Qf,dd:d}]})},Rb=()=>{},Yf,X=a=>{for(var b=
"";q()[a];)b+=Yf[q()[a++]];return b},Y;function Zf(a,b,c={}){var d=b.name;if(!a)throw new Y(`type "${d}" must have a positive integer typeid pointer`);if(Sf.hasOwnProperty(a)){if(c.Hf)return;throw new Y(`Cannot register type '${d}' twice`);}Sf[a]=b;delete Tf[a];Rf.hasOwnProperty(a)&&(b=Rf[a],delete Rf[a],b.forEach(e=>e()))}function Vf(a,b,c={}){return Zf(a,b,c)}
var Xf=8,Sb=(a,b,c,d)=>{b=X(b);Vf(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},cd:Xf,readValueFromPointer:function(e){return this.fromWireType(q()[e])},dd:null})},$f=a=>{throw new Y(a.Gc.Rc.Qc.name+" instance already deleted");},ag=!1,bg=()=>{},cg=(a,b,c)=>{if(b===c)return a;if(void 0===c.Yc)return null;a=cg(a,b,c.Yc);return null===a?null:c.uf(a)},dg={},eg={},fg=(a,b)=>{if(void 0===b)throw new Y("ptr should not be undefined");for(;a.Yc;)b=a.be(b),a=a.Yc;return eg[b]},
hg=(a,b)=>{if(!b.Rc||!b.Lc)throw new Uf("makeClassHandle requires ptr and ptrType");if(!!b.bd!==!!b.Wc)throw new Uf("Both smartPtrType and smartPtr must be specified");b.count={value:1};return gg(Object.create(a,{Gc:{value:b,writable:!0}}))},gg=a=>{if("undefined"===typeof FinalizationRegistry)return gg=b=>b,a;ag=new FinalizationRegistry(b=>{b=b.Gc;--b.count.value;0===b.count.value&&(b.Wc?b.bd.od(b.Wc):b.Rc.Qc.od(b.Lc))});gg=b=>{var c=b.Gc;c.Wc&&ag.register(b,{Gc:c},b);return b};bg=b=>{ag.unregister(b)};
return gg(a)},ig=[];function jg(){}
var kg=(a,b)=>Object.defineProperty(b,"name",{value:a}),lg=(a,b)=>{var c=z;if(void 0===c[a].gd){var d=c[a];c[a]=function(...e){if(!c[a].gd.hasOwnProperty(e.length))throw new Y(`Function '${b}' called with an invalid number of arguments (${e.length}) - expects one of (${c[a].gd})!`);return c[a].gd[e.length].apply(this,e)};c[a].gd=[];c[a].gd[d.Me]=d}},mg=(a,b,c)=>{if(z.hasOwnProperty(a)){if(void 0===c||void 0!==z[a].gd&&void 0!==z[a].gd[c])throw new Y(`Cannot register public name '${a}' twice`);lg(a,
a);if(z[a].gd.hasOwnProperty(c))throw new Y(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);z[a].gd[c]=b}else z[a]=b,z[a].Me=c},ng=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function og(a,b,c,d,e,f,h,k){this.name=a;this.constructor=b;this.Xd=c;this.od=d;this.Yc=e;this.Af=f;this.be=h;this.uf=k}
var pg=(a,b,c)=>{for(;b!==c;){if(!b.be)throw new Y(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.be(a);b=b.Yc}return a};function qg(a,b){if(null===b){if(this.ye)throw new Y(`null is not a valid ${this.name}`);return 0}if(!b.Gc)throw new Y(`Cannot pass "${rg(b)}" as a ${this.name}`);if(!b.Gc.Lc)throw new Y(`Cannot pass deleted object as a pointer of type ${this.name}`);return pg(b.Gc.Lc,b.Gc.Rc.Qc,this.Qc)}
function sg(a,b){if(null===b){if(this.ye)throw new Y(`null is not a valid ${this.name}`);if(this.ie){var c=this.Ce();null!==a&&a.push(this.od,c);return c}return 0}if(!b||!b.Gc)throw new Y(`Cannot pass "${rg(b)}" as a ${this.name}`);if(!b.Gc.Lc)throw new Y(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.he&&b.Gc.Rc.he)throw new Y(`Cannot convert argument of type ${b.Gc.bd?b.Gc.bd.name:b.Gc.Rc.name} to parameter type ${this.name}`);c=pg(b.Gc.Lc,b.Gc.Rc.Qc,this.Qc);if(this.ie){if(void 0===
b.Gc.Wc)throw new Y("Passing raw pointer to smart pointer is illegal");switch(this.Tf){case 0:if(b.Gc.bd===this)c=b.Gc.Wc;else throw new Y(`Cannot convert argument of type ${b.Gc.bd?b.Gc.bd.name:b.Gc.Rc.name} to parameter type ${this.name}`);break;case 1:c=b.Gc.Wc;break;case 2:if(b.Gc.bd===this)c=b.Gc.Wc;else{var d=b.clone();c=this.Of(c,tg(()=>d["delete"]()));null!==a&&a.push(this.od,c)}break;default:throw new Y("Unsupporting sharing policy");}}return c}
function ug(a,b){if(null===b){if(this.ye)throw new Y(`null is not a valid ${this.name}`);return 0}if(!b.Gc)throw new Y(`Cannot pass "${rg(b)}" as a ${this.name}`);if(!b.Gc.Lc)throw new Y(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.Gc.Rc.he)throw new Y(`Cannot convert argument of type ${b.Gc.Rc.name} to parameter type ${this.name}`);return pg(b.Gc.Lc,b.Gc.Rc.Qc,this.Qc)}
function vg(a,b,c,d,e,f,h,k,l,n,m){this.name=a;this.Qc=b;this.ye=c;this.he=d;this.ie=e;this.Nf=f;this.Tf=h;this.bf=k;this.Ce=l;this.Of=n;this.od=m;e||void 0!==b.Yc?this.toWireType=sg:(this.toWireType=d?qg:ug,this.dd=null)}
var wg=(a,b,c)=>{if(!z.hasOwnProperty(a))throw new Uf("Replacing nonexistent public symbol");void 0!==z[a].gd&&void 0!==c?z[a].gd[c]=b:(z[a]=b,z[a].Me=c)},xg=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,z["dynCall_"+a])(b,...c)):b=M.get(b)(...c);return b},yg=(a,b)=>(...c)=>xg(a,b,c),zg=(a,b)=>{a=X(a);var c=a.includes("j")?yg(a,b):M.get(b);if("function"!=typeof c)throw new Y(`unknown function pointer with signature ${a}: ${b}`);return c},Ag,Dg=a=>{a=Bg(a);var b=X(a);Cg(a);return b},Eg=
(a,b)=>{function c(f){e[f]||Sf[f]||(Tf[f]?Tf[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Ag(`${a}: `+d.map(Dg).join([", "]));},Tb=(a,b,c,d,e,f,h,k,l,n,m,r,x)=>{m=X(m);f=zg(e,f);k&&=zg(h,k);n&&=zg(l,n);x=zg(r,x);var D=ng(m);mg(D,function(){Eg(`Cannot construct ${m} due to unbound types`,[d])});Wf([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var y=v.Qc;var L=y.Xd}else L=jg.prototype;v=kg(m,function(...T){if(Object.getPrototypeOf(this)!==J)throw new Y("Use 'new' to construct "+m);if(void 0===
K.Cd)throw new Y(m+" has no accessible constructor");var se=K.Cd[T.length];if(void 0===se)throw new Y(`Tried to invoke ctor of ${m} with invalid number of parameters (${T.length}) - expected (${Object.keys(K.Cd).toString()}) parameters instead!`);return se.apply(this,T)});var J=Object.create(L,{constructor:{value:v}});v.prototype=J;var K=new og(m,v,J,x,y,f,k,n);if(K.Yc){var ma;(ma=K.Yc).Ke??(ma.Ke=[]);K.Yc.Ke.push(K)}y=new vg(m,K,!0,!1,!1);ma=new vg(m+"*",K,!1,!1,!1);L=new vg(m+" const*",K,!1,!0,
!1);dg[a]={pointerType:ma,sf:L};wg(D,v);return[y,ma,L]})},Fg=[],Gg=[],pc=a=>{9<a&&0===--Gg[a+1]&&(Gg[a]=void 0,Fg.push(a))},Hg=a=>{if(!a)throw new Y("Cannot use deleted val. handle = "+a);return Gg[a]},tg=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Fg.pop()||Gg.length;Gg[b]=a;Gg[b+1]=1;return b}},Ig={name:"emscripten::val",fromWireType:a=>{var b=Hg(a);pc(a);return b},toWireType:(a,b)=>tg(b),cd:Xf,readValueFromPointer:Qf,dd:null},Ub=a=>Vf(a,
Ig),Jg=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.fromWireType(g()[d])}:function(d){return this.fromWireType(q()[d])};case 2:return c?function(d){return this.fromWireType(t()[d>>1])}:function(d){return this.fromWireType(ea()[d>>1])};case 4:return c?function(d){return this.fromWireType(u()[d>>2])}:function(d){return this.fromWireType(w()[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Vb=(a,b,c,d)=>{function e(){}b=X(b);e.values={};Vf(a,{name:b,constructor:e,
fromWireType:function(f){return this.constructor.values[f]},toWireType:(f,h)=>h.value,cd:Xf,readValueFromPointer:Jg(b,c,d),dd:null});mg(b,e)},Kg=(a,b)=>{var c=Sf[a];if(void 0===c)throw a=`${b} has unknown type ${Dg(a)}`,new Y(a);return c},Wb=(a,b,c)=>{var d=Kg(a,"enum");b=X(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:kg(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},rg=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===
b||"function"===b?a.toString():""+a},Lg=(a,b)=>{switch(b){case 4:return function(c){var d=this.fromWireType;p.buffer!=aa.buffer&&ba();return d.call(this,ya[c>>2])};case 8:return function(c){return this.fromWireType(ja()[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Xb=(a,b,c)=>{b=X(b);Vf(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,cd:Xf,readValueFromPointer:Lg(b,c),dd:null})};
function Mg(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].dd)return!0;return!1}
function Ng(a,b,c,d){var e=b.length;if(2>e)throw new Y("argTypes array size mismatch! Must at least get return value and 'this' types!");var f=null!==b[1]&&!1,h=Mg(b),k="void"!==b[0].name,l=e-2,n=Array(l),m=[],r=[];return kg(a,function(...x){r.length=0;m.length=f?2:1;m[0]=d;if(f){var D=b[1].toWireType(r,this);m[1]=D}for(var v=0;v<l;++v)n[v]=b[v+2].toWireType(r,x[v]),m.push(n[v]);x=c(...m);if(h)Pf(r);else for(v=f?1:2;v<b.length;v++){var y=1===v?D:n[v-2];null!==b[v].dd&&b[v].dd(y)}D=k?b[0].fromWireType(x):
void 0;return D})}
var Og=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(w()[b+4*d>>2]);return c},Pg=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Yb=(a,b,c,d,e,f)=>{var h=Og(b,c);a=X(a);a=Pg(a);e=zg(d,e);mg(a,function(){Eg(`Cannot call ${a} due to unbound types`,h)},b-1);Wf([],h,k=>{wg(a,Ng(a,[k[0],null].concat(k.slice(1)),e,f),b-1);return[]})},Qg=(a,b,c)=>{switch(b){case 1:return c?d=>g()[d]:d=>q()[d];case 2:return c?d=>t()[d>>1]:d=>ea()[d>>1];case 4:return c?d=>u()[d>>2]:d=>w()[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}},Zb=(a,b,c,d,e)=>{b=X(b);-1===e&&(e=4294967295);e=k=>k;if(0===d){var f=32-8*c;e=k=>k<<f>>>f}var h=b.includes("unsigned")?function(k,l){return l>>>0}:function(k,l){return l};Vf(a,{name:b,fromWireType:e,toWireType:h,cd:Xf,readValueFromPointer:Qg(b,c,0!==d),dd:null})},$b=(a,b,c)=>{function d(f){var h=w()[f>>2];f=w()[f+4>>2];return new e(g().buffer,f,h)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=X(c);Vf(a,{name:c,fromWireType:d,cd:Xf,readValueFromPointer:d},
{Hf:!0})},ac=(a,b)=>{b=X(b);var c="std::string"===b;Vf(a,{name:b,fromWireType:function(d){var e=w()[d>>2],f=d+4;if(c)for(var h=f,k=0;k<=e;++k){var l=f+k;if(k==e||0==q()[l]){h=N(h,l-h);if(void 0===n)var n=h;else n+=String.fromCharCode(0),n+=h;h=l+1}}else{n=Array(e);for(k=0;k<e;++k)n[k]=String.fromCharCode(q()[f+k]);n=n.join("")}Cg(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||
e instanceof Int8Array))throw new Y("Cannot pass non-string to std::string");var h=c&&f?Fe(e):e.length;var k=Rg(4+h+1),l=k+4;w()[k>>2]=h;if(c&&f)h+=1,Ge(e,q(),l,h);else if(f)for(f=0;f<h;++f){var n=e.charCodeAt(f);if(255<n)throw Cg(l),new Y("String has UTF-16 code units that do not fit in 8 bits");q()[l+f]=n}else for(f=0;f<h;++f)q()[l+f]=e[f];null!==d&&d.push(Cg,k);return k},cd:Xf,readValueFromPointer:Qf,dd(d){Cg(d)}})},Sg="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Tg=(a,b)=>
{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ea()[c];)++c;c<<=1;if(32<c-a&&Sg)return Sg.decode(q().slice(a,c));c="";for(d=0;!(d>=b/2);++d){var e=t()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Ug=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);t()[b>>1]=f;b+=2}t()[b>>1]=0;return b-d},Vg=a=>2*a.length,Wg=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=u()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Xg=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}u()[b>>2]=f;b+=4;if(b+4>c)break}u()[b>>2]=0;return b-d},Yg=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},bc=(a,b,c)=>{c=X(c);if(2===b){var d=Tg;var e=Ug;var f=Vg;var h=k=>ea()[k>>1]}else 4===b&&(d=Wg,e=Xg,f=
Yg,h=k=>w()[k>>2]);Vf(a,{name:c,fromWireType:k=>{for(var l=w()[k>>2],n,m=k+4,r=0;r<=l;++r){var x=k+4+r*b;if(r==l||0==h(x))m=d(m,x-m),void 0===n?n=m:(n+=String.fromCharCode(0),n+=m),m=x+b}Cg(k);return n},toWireType:(k,l)=>{if("string"!=typeof l)throw new Y(`Cannot pass non-string to C++ string type ${c}`);var n=f(l),m=Rg(4+n+b);w()[m>>2]=n/b;e(l,m+4,n+b);null!==k&&k.push(Cg,m);return m},cd:Xf,readValueFromPointer:Qf,dd(k){Cg(k)}})},cc=(a,b,c,d,e,f)=>{Of[a]={name:X(b),Ce:zg(c,d),od:zg(e,f),Ue:[]}},
dc=(a,b,c,d,e,f,h,k,l,n)=>{Of[a].Ue.push({xf:X(b),Ef:c,Ud:zg(d,e),Df:f,Rf:h,Qf:zg(k,l),Sf:n})},ec=(a,b)=>{b=X(b);Vf(a,{xg:!0,name:b,cd:0,fromWireType:()=>{},toWireType:()=>{}})},fc=()=>1,gc=a=>{Da(a,!1,1,!0,1048576,!1);Ea()},Zg=a=>{if(!wa)try{if(a(),!(Wd||0<Sd))try{A?ee(xa):Nc(xa)}catch(b){Xd(b)}}catch(b){Xd(b)}},Fa=a=>{"function"===typeof Atomics.Zf&&(Atomics.Zf(u(),a>>2,a).value.then(Ia),a+=128,Atomics.store(u(),a>>2,1))},Ia=()=>{var a=Ba();a&&(Fa(a),Zg($g))},hc=(a,b)=>{a==b?setTimeout(Ia):A?postMessage({pe:a,
jd:"checkMailbox"}):(a=Qd[a])&&a.postMessage({jd:"checkMailbox"})},ah=[],ic=(a,b,c,d,e)=>{ah.length=d;b=e>>3;for(c=0;c<d;c++)ah[c]=ja()[b+c];return(0,bh[a])(...ah)},jc=()=>{Wd=!1;Sd=0},kc=a=>a?-52:0,lc=a=>{A?postMessage({jd:"cleanupThread",Wf:a}):ce(Qd[a])},mc=()=>{},nc=()=>{throw Infinity;},ch={},dh=a=>{var b=ch[a];return void 0===b?X(a):b},eh=[],oc=(a,b,c,d,e)=>{a=eh[a];b=Hg(b);c=dh(c);return a(b,b[c],d,e)},fh=a=>{var b=eh.length;eh.push(a);return b},gh=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=
Kg(w()[b+4*d>>2],"parameter "+d);return c},hh=Reflect.construct,qc=(a,b,c)=>{var d=gh(a,b),e=d.shift();a--;var f=Array(a);b=`methodCaller<(${d.map(h=>h.name).join(", ")}) => ${e.name}>`;return fh(kg(b,(h,k,l,n)=>{for(var m=0,r=0;r<a;++r)f[r]=d[r].readValueFromPointer(n+m),m+=d[r].cd;k=1===c?hh(k,f):k.apply(h,f);h=[];k=e.toWireType(h,k);h.length&&(w()[l>>2]=tg(h));return k}))},rc=a=>{9<a&&(Gg[a+1]+=1)},sc=()=>tg([]),tc=a=>tg(dh(a)),uc=()=>tg({}),vc=a=>{var b=Hg(a);Pf(b);pc(a)},wc=(a,b,c)=>{a=Hg(a);
b=Hg(b);c=Hg(c);a[b]=c},xc=(a,b)=>{a=Kg(a,"_emval_take_value");a=a.readValueFromPointer(b);return tg(a)};function yc(a,b,c){a=new Date(1E3*Td(a,b));u()[c>>2]=a.getUTCSeconds();u()[c+4>>2]=a.getUTCMinutes();u()[c+8>>2]=a.getUTCHours();u()[c+12>>2]=a.getUTCDate();u()[c+16>>2]=a.getUTCMonth();u()[c+20>>2]=a.getUTCFullYear()-1900;u()[c+24>>2]=a.getUTCDay();a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;u()[c+28>>2]=a}
var ih=[0,31,60,91,121,152,182,213,244,274,305,335],jh=[0,31,59,90,120,151,181,212,243,273,304,334];
function zc(a){var b=new Date(u()[a+20>>2]+1900,u()[a+16>>2],u()[a+12>>2],u()[a+8>>2],u()[a+4>>2],u()[a>>2],0),c=u()[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),h=Math.min(f,e);0>c?u()[a+32>>2]=Number(e!=f&&h==d):0<c!=(h==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?h:e)-d)));u()[a+24>>2]=b.getDay();c=b.getFullYear();c=(0!==c%4||0===c%100&&0!==c%400?jh:ih)[b.getMonth()]+b.getDate()-1|0;u()[a+28>>
2]=c;u()[a>>2]=b.getSeconds();u()[a+4>>2]=b.getMinutes();u()[a+8>>2]=b.getHours();u()[a+12>>2]=b.getDate();u()[a+16>>2]=b.getMonth();u()[a+20>>2]=b.getYear();a=b.getTime();a=isNaN(a)?-1:a/1E3;pe((E=a,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0));return a>>>0}
function Ac(a,b,c,d,e,f,h,k){if(A)return I(30,1,a,b,c,d,e,f,h,k);e=Td(e,f);try{if(isNaN(e))return 61;var l=W(d),n=C.xd(l,a,e,b,c),m=n.Lc;u()[h>>2]=n.se;w()[k>>2]=m;return 0}catch(r){if("undefined"==typeof C||"ErrnoError"!==r.name)throw r;return-r.Kc}}
function Bc(a,b,c,d,e,f,h){if(A)return I(31,1,a,b,c,d,e,f,h);f=Td(f,h);try{var k=W(e);if(c&2){if(!C.isFile(k.node.mode))throw new C.Fc(43);if(!(d&2)){var l=q().slice(a,a+b);C.Hd(k,l,f,b,d)}}}catch(n){if("undefined"==typeof C||"ErrnoError"!==n.name)throw n;return-n.Kc}}var kh={},Ic=()=>performance.timeOrigin+performance.now();
function Cc(a,b){if(A)return I(32,1,a,b);kh[a]&&(clearTimeout(kh[a].id),delete kh[a]);if(!b)return 0;var c=setTimeout(()=>{delete kh[a];Zg(()=>lh(a,performance.timeOrigin+performance.now()))},b);kh[a]={id:c,Qg:b};return 0}
var Dc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var h=Math.max(f,e);w()[a>>2]=60*h;u()[b>>2]=Number(f!=e);b=k=>{var l=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Mf(a,c),Mf(b,d)):(Mf(a,d),Mf(b,c))},Ec=()=>{},Fc=()=>Date.now(),Gc=()=>{Sd+=1;throw"unwind";},Hc=()=>2147483648,Jc=()=>navigator.hardwareConcurrency,Kc=a=>{var b=q().length;
a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-p.buffer.byteLength+65535)/65536|0;try{p.grow(d);ba();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},mh={},oh=()=>{if(!nh){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:"./this.program"},
b;for(b in mh)void 0===mh[b]?delete a[b]:a[b]=mh[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);nh=c}return nh},nh;function Lc(a,b){if(A)return I(33,1,a,b);var c=0;oh().forEach((d,e)=>{var f=b+c;e=w()[a+4*e>>2]=f;for(f=0;f<d.length;++f)g()[e++]=d.charCodeAt(f);g()[e]=0;c+=d.length+1});return 0}function Mc(a,b){if(A)return I(34,1,a,b);var c=oh();w()[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);w()[b>>2]=d;return 0}
function Oc(a){if(A)return I(35,1,a);try{var b=W(a);C.close(b);return 0}catch(c){if("undefined"==typeof C||"ErrnoError"!==c.name)throw c;return c.Kc}}
function Pc(a,b){if(A)return I(36,1,a,b);try{var c=W(a),d=c.Oc?2:Q(c.mode)?3:40960===(c.mode&61440)?7:4;g()[b]=d;t()[b+2>>1]=0;F=[0,(E=0,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];u()[b+8>>2]=F[0];u()[b+12>>2]=F[1];F=[0,(E=0,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];u()[b+16>>2]=F[0];u()[b+20>>2]=F[1];return 0}catch(e){if("undefined"==typeof C||"ErrnoError"!==e.name)throw e;return e.Kc}}
var ph=(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var h=w()[b>>2],k=w()[b+4>>2];b+=8;h=C.read(a,g(),h,k,d);if(0>h)return-1;e+=h;if(h<k)break;"undefined"!=typeof d&&(d+=h)}return e};function Qc(a,b,c,d,e,f){if(A)return I(37,1,a,b,c,d,e,f);d=Td(d,e);try{if(isNaN(d))return 61;var h=W(a),k=ph(h,b,c,d);w()[f>>2]=k;return 0}catch(l){if("undefined"==typeof C||"ErrnoError"!==l.name)throw l;return l.Kc}}
var qh=(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var h=w()[b>>2],k=w()[b+4>>2];b+=8;h=C.write(a,g(),h,k,d);if(0>h)return-1;e+=h;if(h<k)break;"undefined"!=typeof d&&(d+=h)}return e};function Rc(a,b,c,d,e,f){if(A)return I(38,1,a,b,c,d,e,f);d=Td(d,e);try{if(isNaN(d))return 61;var h=W(a),k=qh(h,b,c,d);w()[f>>2]=k;return 0}catch(l){if("undefined"==typeof C||"ErrnoError"!==l.name)throw l;return l.Kc}}
function Sc(a,b,c,d){if(A)return I(39,1,a,b,c,d);try{var e=W(a),f=ph(e,b,c);w()[d>>2]=f;return 0}catch(h){if("undefined"==typeof C||"ErrnoError"!==h.name)throw h;return h.Kc}}
function Tc(a,b,c,d,e){if(A)return I(40,1,a,b,c,d,e);b=Td(b,c);try{if(isNaN(b))return 61;var f=W(a);C.Vc(f,b,d);F=[f.position>>>0,(E=f.position,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];u()[e>>2]=F[0];u()[e+4>>2]=F[1];f.Fd&&0===b&&0===d&&(f.Fd=null);return 0}catch(h){if("undefined"==typeof C||"ErrnoError"!==h.name)throw h;return h.Kc}}
function Uc(a){if(A)return I(41,1,a);try{var b=W(a);return b.Ic?.Ld?b.Ic.Ld(b):0}catch(c){if("undefined"==typeof C||"ErrnoError"!==c.name)throw c;return c.Kc}}function Vc(a,b,c,d){if(A)return I(42,1,a,b,c,d);try{var e=W(a),f=qh(e,b,c);w()[d>>2]=f;return 0}catch(h){if("undefined"==typeof C||"ErrnoError"!==h.name)throw h;return h.Kc}}
function Wc(a,b,c,d){function e(r,x,D,v,y,L){var J=10===r?28:16;y=10===r?Ff(y):Df(y);J=Rg(J);!yf(J,r,y,L)||Va();y=Rg(32);u()[y+4>>2]=r;u()[y+8>>2]=x;u()[y+12>>2]=D;w()[y+24>>2]=v;w()[y+20>>2]=J;10===r?u()[y+16>>2]=28:u()[y+16>>2]=16;u()[y+28>>2]=0;return y}if(A)return I(43,1,a,b,c,d);var f=0,h=0,k=0,l=0,n=0,m=0;c&&(k=u()[c>>2],l=u()[c+4>>2],n=u()[c+8>>2],m=u()[c+12>>2]);n&&!m&&(m=2===n?17:6);!n&&m&&(n=17===m?2:1);0===m&&(m=6);0===n&&(n=1);if(!a&&!b)return-2;if(k&-1088||0!==c&&u()[c>>2]&2&&!a)return-1;
if(k&32)return-2;if(0!==n&&1!==n&&2!==n)return-7;if(0!==l&&2!==l&&10!==l)return-6;if(b&&(b=N(b),h=parseInt(b,10),isNaN(h)))return k&1024?-2:-8;if(!a)return 0===l&&(l=2),0===(k&1)&&(2===l?f=rh(2130706433):f=[0,0,0,rh(1)]),a=e(l,n,m,null,f,h),w()[d>>2]=a,0;a=N(a);f=vf(a);if(null!==f)if(0===l||2===l)l=2;else if(10===l&&k&8)f=[0,0,rh(65535),f],l=10;else return-2;else if(f=xf(a),null!==f)if(0===l||10===l)l=10;else return-2;if(null!=f)return a=e(l,n,m,a,f,h),w()[d>>2]=a,0;if(k&4)return-2;a=Cf(a);f=vf(a);
0===l?l=2:10===l&&(f=[0,0,rh(65535),f]);a=e(l,n,m,null,f,h);w()[d>>2]=a;return 0}function Jd(a,b){try{return ve(q().subarray(a,a+b)),0}catch(c){if("undefined"==typeof C||"ErrnoError"!==c.name)throw c;return c.Kc}}A||$d();
C.og=(a,b,c,d,e,f,h,k,l,n)=>{function m(x){function D(v){n?.();if(!k){var y=a,L=b;y&&(y="string"==typeof y?y:$e(y),L=b?xe(y+"/"+b):y);y=Ue(d,e);L=C.create(L,y);if(v){if("string"==typeof v){for(var J=Array(v.length),K=0,ma=v.length;K<ma;++K)J[K]=v.charCodeAt(K);v=J}kf(L,y|146);J=C.open(L,577);C.write(J,v,0,v.length,0,l);C.close(J);kf(L,y)}}f?.();Ua()}Te(x,r,D,()=>{h?.();Ua()})||D(x)}var r=b?Ce(xe(a+"/"+b)):a;Ra++;"string"==typeof c?Re(c,m,h):m(c)};C.ef();P.Se=new C.Fc(44);P.Se.stack="<generic error, no stack>";
Uf=z.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var sh=Array(256),th=0;256>th;++th)sh[th]=String.fromCharCode(th);Yf=sh;Y=z.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(jg.prototype,{isAliasOf:function(a){if(!(this instanceof jg&&a instanceof jg))return!1;var b=this.Gc.Rc.Qc,c=this.Gc.Lc;a.Gc=a.Gc;var d=a.Gc.Rc.Qc;for(a=a.Gc.Lc;b.Yc;)c=b.be(c),b=b.Yc;for(;d.Yc;)a=d.be(a),d=d.Yc;return b===d&&c===a},clone:function(){this.Gc.Lc||$f(this);if(this.Gc.$d)return this.Gc.count.value+=1,this;var a=gg,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Gc;a=a(c.call(b,d,{Gc:{value:{count:e.count,Td:e.Td,$d:e.$d,Lc:e.Lc,Rc:e.Rc,Wc:e.Wc,bd:e.bd}}}));a.Gc.count.value+=
1;a.Gc.Td=!1;return a},["delete"](){this.Gc.Lc||$f(this);if(this.Gc.Td&&!this.Gc.$d)throw new Y("Object already scheduled for deletion");bg(this);var a=this.Gc;--a.count.value;0===a.count.value&&(a.Wc?a.bd.od(a.Wc):a.Rc.Qc.od(a.Lc));this.Gc.$d||(this.Gc.Wc=void 0,this.Gc.Lc=void 0)},isDeleted:function(){return!this.Gc.Lc},deleteLater:function(){this.Gc.Lc||$f(this);if(this.Gc.Td&&!this.Gc.$d)throw new Y("Object already scheduled for deletion");ig.push(this);this.Gc.Td=!0;return this}});
Object.assign(vg.prototype,{Cf(a){this.bf&&(a=this.bf(a));return a},Qe(a){this.od?.(a)},cd:Xf,readValueFromPointer:Qf,fromWireType:function(a){function b(){return this.ie?hg(this.Qc.Xd,{Rc:this.Nf,Lc:c,bd:this,Wc:a}):hg(this.Qc.Xd,{Rc:this,Lc:a})}var c=this.Cf(a);if(!c)return this.Qe(a),null;var d=fg(this.Qc,c);if(void 0!==d){if(0===d.Gc.count.value)return d.Gc.Lc=c,d.Gc.Wc=a,d.clone();d=d.clone();this.Qe(a);return d}d=this.Qc.Af(c);d=dg[d];if(!d)return b.call(this);d=this.he?d.sf:d.pointerType;var e=
cg(c,this.Qc,d.Qc);return null===e?b.call(this):this.ie?hg(d.Qc.Xd,{Rc:d,Lc:e,bd:this,Wc:a}):hg(d.Qc.Xd,{Rc:d,Lc:e})}});Ag=z.UnboundTypeError=((a,b)=>{var c=kg(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
Gg.push(0,1,void 0,1,null,1,!0,1,!1,1);z.count_emval_handles=()=>Gg.length/2-5-Fg.length;
var bh=[Id,Yd,te,ob,pb,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Ac,Bc,Cc,Lc,Mc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc],bb,Z=function(){function a(c,d){Z=c.exports;Zd.push(Z.Qb);M=Z.Sb;La.unshift(Z.Hb);va=d;Ua();return Z}Ra++;var b=ab();if(z.instantiateWasm)try{return z.instantiateWasm(b,a)}catch(c){B(`Module.instantiateWasm callback failed with error: ${c}`),na(c)}if(A)return new Promise(c=>{za=d=>{var e=new WebAssembly.Instance(d,ab());a(e,d);c()}});Xa??=Wa("magick.wasm")?"magick.wasm":
z.locateFile?z.locateFile("magick.wasm",ra):ra+"magick.wasm";$a(b,function(c){a(c.instance,c.module)}).catch(na);return{}}(),Bg=a=>(Bg=Z.Ib)(a),Ga=z.__embind_initialize_bindings=()=>(Ga=z.__embind_initialize_bindings=Z.Jb)(),uh=z._main=(a,b)=>(uh=z._main=Z.Kb)(a,b),Ba=()=>(Ba=Z.Lb)(),Cg=a=>(Cg=Z.Mb)(a),Rg=a=>(Rg=Z.Nb)(a),oe=a=>(oe=Z.Ob)(a),le=a=>(le=Z.Pb)(a),Ne=(a,b)=>(Ne=Z.Rb)(a,b),Da=(a,b,c,d,e,f)=>(Da=Z.Tb)(a,b,c,d,e,f),Ja=z.__emscripten_thread_crashed=()=>(Ja=z.__emscripten_thread_crashed=Z.Ub)(),
rh=a=>(rh=Z.Vb)(a),wf=a=>(wf=Z.Wb)(a),Ef=a=>(Ef=Z.Xb)(a),Vd=(a,b,c,d,e)=>(Vd=Z.Yb)(a,b,c,d,e),be=a=>(be=Z.Zb)(a),ee=a=>(ee=Z._b)(a),lh=(a,b)=>(lh=Z.$b)(a,b),$g=()=>($g=Z.ac)(),O=(a,b)=>(O=Z.bc)(a,b),pe=a=>(pe=Z.cc)(a),de=(a,b)=>(de=Z.dc)(a,b),H=a=>(H=Z.ec)(a),Ud=a=>(Ud=Z.fc)(a),G=()=>(G=Z.gc)(),qe=(a,b,c)=>(qe=Z.hc)(a,b,c),me=a=>(me=Z.ic)(a),vh=z.dynCall_jiji=(a,b,c,d,e)=>(vh=z.dynCall_jiji=Z.jc)(a,b,c,d,e);z.dynCall_jjii=(a,b,c,d,e)=>(z.dynCall_jjii=Z.kc)(a,b,c,d,e);
var wh=z.dynCall_ji=(a,b)=>(wh=z.dynCall_ji=Z.lc)(a,b),xh=z.dynCall_viiji=(a,b,c,d,e,f)=>(xh=z.dynCall_viiji=Z.mc)(a,b,c,d,e,f),yh=z.dynCall_iiijj=(a,b,c,d,e,f,h)=>(yh=z.dynCall_iiijj=Z.nc)(a,b,c,d,e,f,h),zh=z.dynCall_iij=(a,b,c,d)=>(zh=z.dynCall_iij=Z.oc)(a,b,c,d),Ah=z.dynCall_vij=(a,b,c,d)=>(Ah=z.dynCall_vij=Z.pc)(a,b,c,d),Bh=z.dynCall_j=a=>(Bh=z.dynCall_j=Z.qc)(a);z.dynCall_viij=(a,b,c,d,e)=>(z.dynCall_viij=Z.rc)(a,b,c,d,e);z.dynCall_iijji=(a,b,c,d,e,f,h)=>(z.dynCall_iijji=Z.sc)(a,b,c,d,e,f,h);
var Ch=z.dynCall_iiiiij=(a,b,c,d,e,f,h)=>(Ch=z.dynCall_iiiiij=Z.tc)(a,b,c,d,e,f,h);z.dynCall_jiiiiiiiii=(a,b,c,d,e,f,h,k,l,n)=>(z.dynCall_jiiiiiiiii=Z.uc)(a,b,c,d,e,f,h,k,l,n);z.dynCall_viijii=(a,b,c,d,e,f,h)=>(z.dynCall_viijii=Z.vc)(a,b,c,d,e,f,h);z.dynCall_iiiiijj=(a,b,c,d,e,f,h,k,l)=>(z.dynCall_iiiiijj=Z.wc)(a,b,c,d,e,f,h,k,l);z.dynCall_iiiiiijj=(a,b,c,d,e,f,h,k,l,n)=>(z.dynCall_iiiiiijj=Z.xc)(a,b,c,d,e,f,h,k,l,n);z.dynCall_jijj=(a,b,c,d,e,f)=>(z.dynCall_jijj=Z.yc)(a,b,c,d,e,f);
z.dynCall_vijj=(a,b,c,d,e,f)=>(z.dynCall_vijj=Z.zc)(a,b,c,d,e,f);z.dynCall_iiijii=(a,b,c,d,e,f,h)=>(z.dynCall_iiijii=Z.Ac)(a,b,c,d,e,f,h);z.dynCall_jiiiiii=(a,b,c,d,e,f,h)=>(z.dynCall_jiiiiii=Z.Bc)(a,b,c,d,e,f,h);z.dynCall_jiiiii=(a,b,c,d,e,f)=>(z.dynCall_jiiiii=Z.Cc)(a,b,c,d,e,f);z.dynCall_jiiiiiiii=(a,b,c,d,e,f,h,k,l)=>(z.dynCall_jiiiiiiii=Z.Dc)(a,b,c,d,e,f,h,k,l);z.dynCall_iiji=(a,b,c,d,e)=>(z.dynCall_iiji=Z.Ec)(a,b,c,d,e);
function wd(a,b,c,d,e){var f=G();try{M.get(a)(b,c,d,e)}catch(h){H(f);if(h!==h+0)throw h;O(1,0)}}function fd(a,b,c,d,e,f,h){var k=G();try{return M.get(a)(b,c,d,e,f,h)}catch(l){H(k);if(l!==l+0)throw l;O(1,0)}}function ad(a,b,c){var d=G();try{return M.get(a)(b,c)}catch(e){H(d);if(e!==e+0)throw e;O(1,0)}}function bd(a,b,c,d){var e=G();try{return M.get(a)(b,c,d)}catch(f){H(e);if(f!==f+0)throw f;O(1,0)}}
function cd(a,b,c,d,e){var f=G();try{return M.get(a)(b,c,d,e)}catch(h){H(f);if(h!==h+0)throw h;O(1,0)}}function Ad(a,b,c,d,e,f,h,k,l){var n=G();try{M.get(a)(b,c,d,e,f,h,k,l)}catch(m){H(n);if(m!==m+0)throw m;O(1,0)}}function rd(a,b){var c=G();try{M.get(a)(b)}catch(d){H(c);if(d!==d+0)throw d;O(1,0)}}function Zc(a,b){var c=G();try{return M.get(a)(b)}catch(d){H(c);if(d!==d+0)throw d;O(1,0)}}function sd(a,b,c){var d=G();try{M.get(a)(b,c)}catch(e){H(d);if(e!==e+0)throw e;O(1,0)}}
function ed(a,b,c,d,e,f){var h=G();try{return M.get(a)(b,c,d,e,f)}catch(k){H(h);if(k!==k+0)throw k;O(1,0)}}function Xc(a,b,c){var d=G();try{return M.get(a)(b,c)}catch(e){H(d);if(e!==e+0)throw e;O(1,0)}}function vd(a,b,c,d){var e=G();try{M.get(a)(b,c,d)}catch(f){H(e);if(f!==f+0)throw f;O(1,0)}}function Yc(a){var b=G();try{return M.get(a)()}catch(c){H(b);if(c!==c+0)throw c;O(1,0)}}function qd(a){var b=G();try{M.get(a)()}catch(c){H(b);if(c!==c+0)throw c;O(1,0)}}
function $c(a,b,c,d){var e=G();try{return M.get(a)(b,c,d)}catch(f){H(e);if(f!==f+0)throw f;O(1,0)}}function Bd(a,b,c,d,e,f,h,k,l,n){var m=G();try{M.get(a)(b,c,d,e,f,h,k,l,n)}catch(r){H(m);if(r!==r+0)throw r;O(1,0)}}function td(a,b,c,d){var e=G();try{M.get(a)(b,c,d)}catch(f){H(e);if(f!==f+0)throw f;O(1,0)}}function ud(a,b,c,d,e,f,h,k,l,n,m){var r=G();try{M.get(a)(b,c,d,e,f,h,k,l,n,m)}catch(x){H(r);if(x!==x+0)throw x;O(1,0)}}
function xd(a,b,c,d,e,f){var h=G();try{M.get(a)(b,c,d,e,f)}catch(k){H(h);if(k!==k+0)throw k;O(1,0)}}function yd(a,b,c,d,e,f,h){var k=G();try{M.get(a)(b,c,d,e,f,h)}catch(l){H(k);if(l!==l+0)throw l;O(1,0)}}function dd(a,b,c,d,e,f){var h=G();try{return M.get(a)(b,c,d,e,f)}catch(k){H(h);if(k!==k+0)throw k;O(1,0)}}function gd(a,b,c,d,e,f,h,k){var l=G();try{return M.get(a)(b,c,d,e,f,h,k)}catch(n){H(l);if(n!==n+0)throw n;O(1,0)}}
function zd(a,b,c,d,e,f,h,k){var l=G();try{M.get(a)(b,c,d,e,f,h,k)}catch(n){H(l);if(n!==n+0)throw n;O(1,0)}}function jd(a,b,c,d,e,f,h,k,l,n,m,r){var x=G();try{return M.get(a)(b,c,d,e,f,h,k,l,n,m,r)}catch(D){H(x);if(D!==D+0)throw D;O(1,0)}}function Cd(a,b,c,d,e,f,h,k,l,n,m){var r=G();try{M.get(a)(b,c,d,e,f,h,k,l,n,m)}catch(x){H(r);if(x!==x+0)throw x;O(1,0)}}function Fd(a,b,c,d,e,f,h,k,l,n,m,r,x,D,v,y){var L=G();try{M.get(a)(b,c,d,e,f,h,k,l,n,m,r,x,D,v,y)}catch(J){H(L);if(J!==J+0)throw J;O(1,0)}}
function Ed(a,b,c,d,e,f,h,k,l,n,m,r,x){var D=G();try{M.get(a)(b,c,d,e,f,h,k,l,n,m,r,x)}catch(v){H(D);if(v!==v+0)throw v;O(1,0)}}function hd(a,b,c,d,e,f,h,k,l,n,m){var r=G();try{return M.get(a)(b,c,d,e,f,h,k,l,n,m)}catch(x){H(r);if(x!==x+0)throw x;O(1,0)}}function Dd(a,b,c,d,e,f,h,k,l,n,m,r){var x=G();try{M.get(a)(b,c,d,e,f,h,k,l,n,m,r)}catch(D){H(x);if(D!==D+0)throw D;O(1,0)}}function ld(a,b,c,d,e,f,h){var k=G();try{return yh(a,b,c,d,e,f,h)}catch(l){H(k);if(l!==l+0)throw l;O(1,0)}}
function md(a,b,c,d){var e=G();try{return zh(a,b,c,d)}catch(f){H(e);if(f!==f+0)throw f;O(1,0)}}function Hd(a,b,c,d){var e=G();try{Ah(a,b,c,d)}catch(f){H(e);if(f!==f+0)throw f;O(1,0)}}function od(a,b){var c=G();try{return wh(a,b)}catch(d){H(c);if(d!==d+0)throw d;O(1,0)}}function pd(a,b,c,d,e){var f=G();try{return vh(a,b,c,d,e)}catch(h){H(f);if(h!==h+0)throw h;O(1,0)}}function nd(a){var b=G();try{return Bh(a)}catch(c){H(b);if(c!==c+0)throw c;O(1,0)}}
function Gd(a,b,c,d,e,f){var h=G();try{xh(a,b,c,d,e,f)}catch(k){H(h);if(k!==k+0)throw k;O(1,0)}}function kd(a,b,c,d,e,f,h){var k=G();try{return Ch(a,b,c,d,e,f,h)}catch(l){H(k);if(l!==l+0)throw l;O(1,0)}}z.callMain=Dh;z.ENV=mh;z.FS=C;z.WORKERFS=U;var Eh;Ta=function Fh(){Eh||Gh();Eh||(Ta=Fh)};
function Dh(a=[]){var b=uh;a.unshift("./this.program");var c=a.length,d=Ud(4*(c+1)),e=d;a.forEach(h=>{var k=w(),l=e>>2,n=Fe(h)+1,m=Ud(n);Ge(h,q(),m,n);k[l]=m;e+=4});w()[e>>2]=0;try{var f=b(c,d);Nc(f,!0);return f}catch(h){return Xd(h)}}function Gh(){if(!(0<Ra))if(A)la(z),Oa(),startWorker(z);else{if(z.preRun)for("function"==typeof z.preRun&&(z.preRun=[z.preRun]);z.preRun.length;)Ka.unshift(z.preRun.shift());Qa(Ka);0<Ra||Eh||(Eh=!0,z.calledRun=!0,wa||(Oa(),A||Qa(Ma),la(z),Hh&&Dh(qa),A||Qa(Na)))}}
var Hh=!0;z.noInitialRun&&(Hh=!1);Gh();Object.assign(C,{init:C.Vd,mkdir:C.ad,mount:C.Nc,chdir:C.qf,writeFile:C.cg,readFile:C.Pf,createLazyFile:C.tf,setIgnorePermissions:function(a){C.ve=a}});moduleRtn=oa;


  return moduleRtn;
}
);
})();
export default init;
var isPthread = globalThis.self?.name?.startsWith('em-pthread');
// When running as a pthread, construct a new instance on startup
isPthread && init();
